In [13]:
# 分组计算，group by
 
import pandas
import pandas as pd 
df = pd.read_csv('E:\movie.csv')
df.head(10)
df.shape

# 统计，每个导演有多少电影
df.director_name.value_counts()

# 分组，按导演名字分组
grouped = df.groupby('director_name')
grouped # 是一个对象，有多个属性和方法

In [17]:
# 分组后的组信息
grouped.size() #有多少组，每个组中有多少条数据

grouped.groups #组的数据结构是什么

len(grouped) # 有多少组

2398

In [22]:
for name,group in grouped:
    print(name)
    print(type(group))

A. Raven Cruz
<class 'pandas.core.frame.DataFrame'>
Aaron Hann
<class 'pandas.core.frame.DataFrame'>
Aaron Schneider
<class 'pandas.core.frame.DataFrame'>
Aaron Seltzer
<class 'pandas.core.frame.DataFrame'>
Abel Ferrara
<class 'pandas.core.frame.DataFrame'>
Adam Brooks
<class 'pandas.core.frame.DataFrame'>
Adam Carolla
<class 'pandas.core.frame.DataFrame'>
Adam Goldberg
<class 'pandas.core.frame.DataFrame'>
Adam Green
<class 'pandas.core.frame.DataFrame'>
Adam Jay Epstein
<class 'pandas.core.frame.DataFrame'>
Adam Marcus
<class 'pandas.core.frame.DataFrame'>
Adam McKay
<class 'pandas.core.frame.DataFrame'>
Adam Rapp
<class 'pandas.core.frame.DataFrame'>
Adam Rifkin
<class 'pandas.core.frame.DataFrame'>
Adam Shankman
<class 'pandas.core.frame.DataFrame'>
Adrian Lyne
<class 'pandas.core.frame.DataFrame'>
Adrienne Shelly
<class 'pandas.core.frame.DataFrame'>
Agnieszka Holland
<class 'pandas.core.frame.DataFrame'>
Agnieszka Wojtowicz-Vosloo
<class 'pandas.core.frame.DataFrame'>
Agustín Díaz Yanes
<class 'pandas.core.frame.DataFrame'>
Aki Kaurismäki
<class 'pandas.core.frame.DataFrame'>
Akira Kurosawa
<class 'pandas.core.frame.DataFrame'>
Akiva Goldsman
<class 'pandas.core.frame.DataFrame'>
Akiva Schaffer
<class 'pandas.core.frame.DataFrame'>
Al Franklin
<class 'pandas.core.frame.DataFrame'>
Al Silliman Jr.
<class 'pandas.core.frame.DataFrame'>
Alain Resnais
<class 'pandas.core.frame.DataFrame'>
Alan Alda
<class 'pandas.core.frame.DataFrame'>
Alan Cohn
<class 'pandas.core.frame.DataFrame'>
Alan J. Pakula
<class 'pandas.core.frame.DataFrame'>
Alan Jacobs
<class 'pandas.core.frame.DataFrame'>
Alan Metter
<class 'pandas.core.frame.DataFrame'>
Alan Parker
<class 'pandas.core.frame.DataFrame'>
Alan Poul
<class 'pandas.core.frame.DataFrame'>
Alan Rudolph
<class 'pandas.core.frame.DataFrame'>
Alan Shapiro
<class 'pandas.core.frame.DataFrame'>
Alan Taylor
<class 'pandas.core.frame.DataFrame'>
Alan Yuen
<class 'pandas.core.frame.DataFrame'>
Albert Brooks
<class 'pandas.core.frame.DataFrame'>
Albert Hughes
<class 'pandas.core.frame.DataFrame'>
Alec Asten
<class 'pandas.core.frame.DataFrame'>
Alejandro Agresti
<class 'pandas.core.frame.DataFrame'>
Alejandro Amenábar
<class 'pandas.core.frame.DataFrame'>
Alejandro G. Iñárritu
<class 'pandas.core.frame.DataFrame'>
Alejandro Monteverde
<class 'pandas.core.frame.DataFrame'>
Aleksandr Veledinskiy
<class 'pandas.core.frame.DataFrame'>
Aleksey German
<class 'pandas.core.frame.DataFrame'>
Alessandro Carloni
<class 'pandas.core.frame.DataFrame'>
Alex Cox
<class 'pandas.core.frame.DataFrame'>
Alex Craig Mann
<class 'pandas.core.frame.DataFrame'>
Alex Garland
<class 'pandas.core.frame.DataFrame'>
Alex Gibney
<class 'pandas.core.frame.DataFrame'>
Alex Kendrick
<class 'pandas.core.frame.DataFrame'>
Alex Proyas
<class 'pandas.core.frame.DataFrame'>
Alex Ranarivelo
<class 'pandas.core.frame.DataFrame'>
Alex Rivera
<class 'pandas.core.frame.DataFrame'>
Alex Smith
<class 'pandas.core.frame.DataFrame'>
Alex Zamm
<class 'pandas.core.frame.DataFrame'>
Alex van Warmerdam
<class 'pandas.core.frame.DataFrame'>
Alexander Payne
<class 'pandas.core.frame.DataFrame'>
Alexander Witt
<class 'pandas.core.frame.DataFrame'>
Alexandre Aja
<class 'pandas.core.frame.DataFrame'>
Alfonso Cuarón
<class 'pandas.core.frame.DataFrame'>
Alfred Hitchcock
<class 'pandas.core.frame.DataFrame'>
Alice Wu
<class 'pandas.core.frame.DataFrame'>
Alison Maclean
<class 'pandas.core.frame.DataFrame'>
Alister Grierson
<class 'pandas.core.frame.DataFrame'>
Allan Arkush
<class 'pandas.core.frame.DataFrame'>
Allan Dwan
<class 'pandas.core.frame.DataFrame'>
Allen Coulter
<class 'pandas.core.frame.DataFrame'>
Allen Hughes
<class 'pandas.core.frame.DataFrame'>
Allison Anders
<class 'pandas.core.frame.DataFrame'>
Allison Burnett
<class 'pandas.core.frame.DataFrame'>
Amal Al-Agroobi
<class 'pandas.core.frame.DataFrame'>
Amanda Gusack
<class 'pandas.core.frame.DataFrame'>
Amat Escalante
<class 'pandas.core.frame.DataFrame'>
Amy Heckerling
<class 'pandas.core.frame.DataFrame'>
Amy Holden Jones
<class 'pandas.core.frame.DataFrame'>
Analeine Cal y Mayor
<class 'pandas.core.frame.DataFrame'>
Anand Tucker
<class 'pandas.core.frame.DataFrame'>
Andrea Arnold
<class 'pandas.core.frame.DataFrame'>
Andrea Di Stefano
<class 'pandas.core.frame.DataFrame'>
Andrei Tarkovsky
<class 'pandas.core.frame.DataFrame'>
Andrew Adamson
<class 'pandas.core.frame.DataFrame'>
Andrew Berends
<class 'pandas.core.frame.DataFrame'>
Andrew Bergman
<class 'pandas.core.frame.DataFrame'>
Andrew Bujalski
<class 'pandas.core.frame.DataFrame'>
Andrew Currie
<class 'pandas.core.frame.DataFrame'>
Andrew Davis
<class 'pandas.core.frame.DataFrame'>
Andrew Dominik
<class 'pandas.core.frame.DataFrame'>
Andrew Douglas
<class 'pandas.core.frame.DataFrame'>
Andrew Erwin
<class 'pandas.core.frame.DataFrame'>
Andrew Fleming
<class 'pandas.core.frame.DataFrame'>
Andrew Haigh
<class 'pandas.core.frame.DataFrame'>
Andrew Hyatt
<class 'pandas.core.frame.DataFrame'>
Andrew Jarecki
<class 'pandas.core.frame.DataFrame'>
Andrew Leman
<class 'pandas.core.frame.DataFrame'>
Andrew Morahan
<class 'pandas.core.frame.DataFrame'>
Andrew Niccol
<class 'pandas.core.frame.DataFrame'>
Andrew Stanton
<class 'pandas.core.frame.DataFrame'>
Andrew Steggall
<class 'pandas.core.frame.DataFrame'>
Andrew Traucki
<class 'pandas.core.frame.DataFrame'>
Andrew Wilson
<class 'pandas.core.frame.DataFrame'>
Andrey Konchalovskiy
<class 'pandas.core.frame.DataFrame'>
Andrey Zvyagintsev
<class 'pandas.core.frame.DataFrame'>
Andrucha Waddington
<class 'pandas.core.frame.DataFrame'>
Andrzej Bartkowiak
<class 'pandas.core.frame.DataFrame'>
André Téchiné
<class 'pandas.core.frame.DataFrame'>
André Øvredal
<class 'pandas.core.frame.DataFrame'>
Andrés Couturier
<class 'pandas.core.frame.DataFrame'>
Andrés Muschietti
<class 'pandas.core.frame.DataFrame'>
Andy Cadiff
<class 'pandas.core.frame.DataFrame'>
Andy Fickman
<class 'pandas.core.frame.DataFrame'>
Andy Garcia
<class 'pandas.core.frame.DataFrame'>
Andy Tennant
<class 'pandas.core.frame.DataFrame'>
Ang Lee
<class 'pandas.core.frame.DataFrame'>
Angela Robinson
<class 'pandas.core.frame.DataFrame'>
Angelina Jolie Pitt
<class 'pandas.core.frame.DataFrame'>
Angelo Pizzo
<class 'pandas.core.frame.DataFrame'>
Anna Boden
<class 'pandas.core.frame.DataFrame'>
Anna Mastro
<class 'pandas.core.frame.DataFrame'>
Anna Muylaert
<class 'pandas.core.frame.DataFrame'>
Annabel Jankel
<class 'pandas.core.frame.DataFrame'>
Anne Fletcher
<class 'pandas.core.frame.DataFrame'>
Anne Fontaine
<class 'pandas.core.frame.DataFrame'>
Anthony Bell
<class 'pandas.core.frame.DataFrame'>
Anthony C. Ferrante
<class 'pandas.core.frame.DataFrame'>
Anthony Hemingway
<class 'pandas.core.frame.DataFrame'>
Anthony Hickox
<class 'pandas.core.frame.DataFrame'>
Anthony Mann
<class 'pandas.core.frame.DataFrame'>
Anthony Minghella
<class 'pandas.core.frame.DataFrame'>
Anthony O'Brien
<class 'pandas.core.frame.DataFrame'>
Anthony Powell
<class 'pandas.core.frame.DataFrame'>
Anthony Russo
<class 'pandas.core.frame.DataFrame'>
Anthony Silverston
<class 'pandas.core.frame.DataFrame'>
Anthony Vallone
<class 'pandas.core.frame.DataFrame'>
Antoine Fuqua
<class 'pandas.core.frame.DataFrame'>
Anton Corbijn
<class 'pandas.core.frame.DataFrame'>
Antonia Bird
<class 'pandas.core.frame.DataFrame'>
Antonio Banderas
<class 'pandas.core.frame.DataFrame'>
Antonio Simoncini
<class 'pandas.core.frame.DataFrame'>
Antony Hoffman
<class 'pandas.core.frame.DataFrame'>
Anurag Basu
<class 'pandas.core.frame.DataFrame'>
Ari Folman
<class 'pandas.core.frame.DataFrame'>
Ari Kirschenbaum
<class 'pandas.core.frame.DataFrame'>
Ari Sandel
<class 'pandas.core.frame.DataFrame'>
Arie Posin
<class 'pandas.core.frame.DataFrame'>
Ariel Vromen
<class 'pandas.core.frame.DataFrame'>
Arjun Sablok
<class 'pandas.core.frame.DataFrame'>
Arthur Hiller
<class 'pandas.core.frame.DataFrame'>
Asger Leth
<class 'pandas.core.frame.DataFrame'>
Asghar Farhadi
<class 'pandas.core.frame.DataFrame'>
Ash Baron-Cohen
<class 'pandas.core.frame.DataFrame'>
Ash Brannon
<class 'pandas.core.frame.DataFrame'>
Ashish R. Mohan
<class 'pandas.core.frame.DataFrame'>
Atom Egoyan
<class 'pandas.core.frame.DataFrame'>
Audrey Wells
<class 'pandas.core.frame.DataFrame'>
Ava DuVernay
<class 'pandas.core.frame.DataFrame'>
Avi Nesher
<class 'pandas.core.frame.DataFrame'>
Ayan Mukerji
<class 'pandas.core.frame.DataFrame'>
Babak Najafi
<class 'pandas.core.frame.DataFrame'>
Babar Ahmed
<class 'pandas.core.frame.DataFrame'>
Baltasar Kormákur
<class 'pandas.core.frame.DataFrame'>
Barbet Schroeder
<class 'pandas.core.frame.DataFrame'>
Barbra Streisand
<class 'pandas.core.frame.DataFrame'>
Barrett Esposito
<class 'pandas.core.frame.DataFrame'>
Barry Cook
<class 'pandas.core.frame.DataFrame'>
Barry Levinson
<class 'pandas.core.frame.DataFrame'>
Barry Skolnick
<class 'pandas.core.frame.DataFrame'>
Barry Sonnenfeld
<class 'pandas.core.frame.DataFrame'>
Barry W. Blaustein
<class 'pandas.core.frame.DataFrame'>
Bart Freundlich
<class 'pandas.core.frame.DataFrame'>
Baz Luhrmann
<class 'pandas.core.frame.DataFrame'>
Becky Smith
<class 'pandas.core.frame.DataFrame'>
Beeban Kidron
<class 'pandas.core.frame.DataFrame'>
Ben Affleck
<class 'pandas.core.frame.DataFrame'>
Ben Falcone
<class 'pandas.core.frame.DataFrame'>
Ben Lewin
<class 'pandas.core.frame.DataFrame'>
Ben Stassen

<class 'pandas.core.frame.DataFrame'>
Ben Stiller
<class 'pandas.core.frame.DataFrame'>
Ben Wheatley
<class 'pandas.core.frame.DataFrame'>
Ben Younger
<class 'pandas.core.frame.DataFrame'>
Benedek Fliegauf
<class 'pandas.core.frame.DataFrame'>
Benedikt Erlingsson
<class 'pandas.core.frame.DataFrame'>
Benh Zeitlin
<class 'pandas.core.frame.DataFrame'>
Benjamin Dickinson
<class 'pandas.core.frame.DataFrame'>
Benjamin Roberds
<class 'pandas.core.frame.DataFrame'>
Bennett Miller
<class 'pandas.core.frame.DataFrame'>
Benni Diez
<class 'pandas.core.frame.DataFrame'>
Benny Boom
<class 'pandas.core.frame.DataFrame'>
Benson Lee
<class 'pandas.core.frame.DataFrame'>
Bernardo Bertolucci
<class 'pandas.core.frame.DataFrame'>
Beto Gómez
<class 'pandas.core.frame.DataFrame'>
Betty Thomas
<class 'pandas.core.frame.DataFrame'>
Bibo Bergeron
<class 'pandas.core.frame.DataFrame'>
Bigas Luna
<class 'pandas.core.frame.DataFrame'>
Bill Benenson
<class 'pandas.core.frame.DataFrame'>
Bill Condon
<class 'pandas.core.frame.DataFrame'>
Bill Duke
<class 'pandas.core.frame.DataFrame'>
Bill Melendez
<class 'pandas.core.frame.DataFrame'>
Bill Muir
<class 'pandas.core.frame.DataFrame'>
Bill Paxton
<class 'pandas.core.frame.DataFrame'>
Bill Plympton
<class 'pandas.core.frame.DataFrame'>
Bille August
<class 'pandas.core.frame.DataFrame'>
Bille Woodruff
<class 'pandas.core.frame.DataFrame'>
Billy Bob Thornton
<class 'pandas.core.frame.DataFrame'>
Billy Kent
<class 'pandas.core.frame.DataFrame'>
Billy Ray
<class 'pandas.core.frame.DataFrame'>
Billy Wilder
<class 'pandas.core.frame.DataFrame'>
Blair Erickson
<class 'pandas.core.frame.DataFrame'>
Blair Hayes
<class 'pandas.core.frame.DataFrame'>
Blake Edwards
<class 'pandas.core.frame.DataFrame'>
Blaz Zavrsnik
<class 'pandas.core.frame.DataFrame'>
Bo Welch
<class 'pandas.core.frame.DataFrame'>
Bo Zenga
<class 'pandas.core.frame.DataFrame'>
Boaz Yakin
<class 'pandas.core.frame.DataFrame'>
Bob Clark
<class 'pandas.core.frame.DataFrame'>
Bob Dolman
<class 'pandas.core.frame.DataFrame'>
Bob Fosse
<class 'pandas.core.frame.DataFrame'>
Bob Giraldi
<class 'pandas.core.frame.DataFrame'>
Bob Gosse
<class 'pandas.core.frame.DataFrame'>
Bob Odenkirk
<class 'pandas.core.frame.DataFrame'>
Bob Rafelson
<class 'pandas.core.frame.DataFrame'>
Bob Saget
<class 'pandas.core.frame.DataFrame'>
Bob Spiers
<class 'pandas.core.frame.DataFrame'>
Bobby Farrelly
<class 'pandas.core.frame.DataFrame'>
Bobby Roth
<class 'pandas.core.frame.DataFrame'>
Bobcat Goldthwait
<class 'pandas.core.frame.DataFrame'>
Bonnie Hunt
<class 'pandas.core.frame.DataFrame'>
Boris Rodriguez
<class 'pandas.core.frame.DataFrame'>
Brad Anderson
<class 'pandas.core.frame.DataFrame'>
Brad Bird
<class 'pandas.core.frame.DataFrame'>
Brad Copeland
<class 'pandas.core.frame.DataFrame'>
Brad Furman
<class 'pandas.core.frame.DataFrame'>
Brad J. Silverman
<class 'pandas.core.frame.DataFrame'>
Brad Peyton
<class 'pandas.core.frame.DataFrame'>
Brad Silberling
<class 'pandas.core.frame.DataFrame'>
Bradley Parker
<class 'pandas.core.frame.DataFrame'>
Bradley Rust Gray
<class 'pandas.core.frame.DataFrame'>
Brandon Camp
<class 'pandas.core.frame.DataFrame'>
Brandon Cronenberg
<class 'pandas.core.frame.DataFrame'>
Brandon Landers
<class 'pandas.core.frame.DataFrame'>
Brandon Trost
<class 'pandas.core.frame.DataFrame'>
Breck Eisner
<class 'pandas.core.frame.DataFrame'>
Brenda Chapman
<class 'pandas.core.frame.DataFrame'>
Brendan Malloy
<class 'pandas.core.frame.DataFrame'>
Brenton Spencer
<class 'pandas.core.frame.DataFrame'>
Brett Leonard
<class 'pandas.core.frame.DataFrame'>
Brett Piper
<class 'pandas.core.frame.DataFrame'>
Brett Ratner
<class 'pandas.core.frame.DataFrame'>
Brian A Miller
<class 'pandas.core.frame.DataFrame'>
Brian Baugh
<class 'pandas.core.frame.DataFrame'>
Brian Caunter
<class 'pandas.core.frame.DataFrame'>
Brian Dannelly
<class 'pandas.core.frame.DataFrame'>
Brian De Palma
<class 'pandas.core.frame.DataFrame'>
Brian Dorton
<class 'pandas.core.frame.DataFrame'>
Brian Gibson
<class 'pandas.core.frame.DataFrame'>
Brian Helgeland
<class 'pandas.core.frame.DataFrame'>
Brian Henson
<class 'pandas.core.frame.DataFrame'>
Brian Klugman
<class 'pandas.core.frame.DataFrame'>
Brian Koppelman
<class 'pandas.core.frame.DataFrame'>
Brian Levant
<class 'pandas.core.frame.DataFrame'>
Brian Percival
<class 'pandas.core.frame.DataFrame'>
Brian Robbins
<class 'pandas.core.frame.DataFrame'>
Brian Trenchard-Smith
<class 'pandas.core.frame.DataFrame'>
Brian Yuzna
<class 'pandas.core.frame.DataFrame'>
Britt Allcroft
<class 'pandas.core.frame.DataFrame'>
Bronwen Hughes
<class 'pandas.core.frame.DataFrame'>
Bruce Beresford
<class 'pandas.core.frame.DataFrame'>
Bruce Campbell
<class 'pandas.core.frame.DataFrame'>
Bruce Dellis
<class 'pandas.core.frame.DataFrame'>
Bruce Hunt
<class 'pandas.core.frame.DataFrame'>
Bruce Macdonald
<class 'pandas.core.frame.DataFrame'>
Bruce Malmuth
<class 'pandas.core.frame.DataFrame'>
Bruce McCulloch
<class 'pandas.core.frame.DataFrame'>
Bruce McDonald
<class 'pandas.core.frame.DataFrame'>
Bruce Paltrow
<class 'pandas.core.frame.DataFrame'>
Bruno Barreto
<class 'pandas.core.frame.DataFrame'>
Bryan Barber
<class 'pandas.core.frame.DataFrame'>
Bryan Singer
<class 'pandas.core.frame.DataFrame'>
Burr Steers
<class 'pandas.core.frame.DataFrame'>
Byron Howard
<class 'pandas.core.frame.DataFrame'>
C. Fraser Press
<class 'pandas.core.frame.DataFrame'>
C. Jay Cox
<class 'pandas.core.frame.DataFrame'>
Cal Brunker
<class 'pandas.core.frame.DataFrame'>
Callie Khouri
<class 'pandas.core.frame.DataFrame'>
Cameron Crowe
<class 'pandas.core.frame.DataFrame'>
Camille Delamarre
<class 'pandas.core.frame.DataFrame'>
Carl Franklin
<class 'pandas.core.frame.DataFrame'>
Carl Rinsch
<class 'pandas.core.frame.DataFrame'>
Carl Theodor Dreyer
<class 'pandas.core.frame.DataFrame'>
Carlos Carrera
<class 'pandas.core.frame.DataFrame'>
Carlos Saldanha
<class 'pandas.core.frame.DataFrame'>
Carlos Saura
<class 'pandas.core.frame.DataFrame'>
Carmen Marron
<class 'pandas.core.frame.DataFrame'>
Carol Reed
<class 'pandas.core.frame.DataFrame'>
Caroline Link
<class 'pandas.core.frame.DataFrame'>
Carroll Ballard
<class 'pandas.core.frame.DataFrame'>
Carter Smith
<class 'pandas.core.frame.DataFrame'>
Cary Bell
<class 'pandas.core.frame.DataFrame'>
Caryn Waechter
<class 'pandas.core.frame.DataFrame'>
Cassandra Nicolaou
<class 'pandas.core.frame.DataFrame'>
Catherine Gund
<class 'pandas.core.frame.DataFrame'>
Catherine Hardwicke
<class 'pandas.core.frame.DataFrame'>
Catherine Jelski
<class 'pandas.core.frame.DataFrame'>
Catherine Owens
<class 'pandas.core.frame.DataFrame'>
Cathy Malkasian
<class 'pandas.core.frame.DataFrame'>
Cecil B. DeMille
<class 'pandas.core.frame.DataFrame'>
Cedric Nicolas-Troyan
<class 'pandas.core.frame.DataFrame'>
Chad Hartigan
<class 'pandas.core.frame.DataFrame'>
Chad Kapper
<class 'pandas.core.frame.DataFrame'>
Chan-wook Park
<class 'pandas.core.frame.DataFrame'>
Chao-Bin Su
<class 'pandas.core.frame.DataFrame'>
Charles Adelman
<class 'pandas.core.frame.DataFrame'>
Charles Binamé
<class 'pandas.core.frame.DataFrame'>
Charles Chaplin
<class 'pandas.core.frame.DataFrame'>
Charles Ferguson
<class 'pandas.core.frame.DataFrame'>
Charles Herman-Wurmfeld
<class 'pandas.core.frame.DataFrame'>
Charles Martin Smith
<class 'pandas.core.frame.DataFrame'>
Charles Matthau
<class 'pandas.core.frame.DataFrame'>
Charles Robert Carner
<class 'pandas.core.frame.DataFrame'>
Charles S. Dutton
<class 'pandas.core.frame.DataFrame'>
Charles Shyer
<class 'pandas.core.frame.DataFrame'>
Charles Stone III
<class 'pandas.core.frame.DataFrame'>
Charles T. Kanganis
<class 'pandas.core.frame.DataFrame'>
Charlie Kaufman
<class 'pandas.core.frame.DataFrame'>
Charlie Levi
<class 'pandas.core.frame.DataFrame'>
Chatrichalerm Yukol
<class 'pandas.core.frame.DataFrame'>
Cheryl Dunye
<class 'pandas.core.frame.DataFrame'>
Chia-Liang Liu
<class 'pandas.core.frame.DataFrame'>
Chris Atkins
<class 'pandas.core.frame.DataFrame'>
Chris Buck
<class 'pandas.core.frame.DataFrame'>
Chris Butler
<class 'pandas.core.frame.DataFrame'>
Chris Carter
<class 'pandas.core.frame.DataFrame'>
Chris Columbus
<class 'pandas.core.frame.DataFrame'>
Chris D'Arienzo
<class 'pandas.core.frame.DataFrame'>
Chris Eyre
<class 'pandas.core.frame.DataFrame'>
Chris Gorak
<class 'pandas.core.frame.DataFrame'>
Chris Kentis
<class 'pandas.core.frame.DataFrame'>
Chris Koch
<class 'pandas.core.frame.DataFrame'>
Chris Marker
<class 'pandas.core.frame.DataFrame'>
Chris Miller
<class 'pandas.core.frame.DataFrame'>
Chris Nahon
<class 'pandas.core.frame.DataFrame'>
Chris Noonan
<class 'pandas.core.frame.DataFrame'>
Chris Paine
<class 'pandas.core.frame.DataFrame'>
Chris Roberts
<class 'pandas.core.frame.DataFrame'>
Chris Robinson
<class 'pandas.core.frame.DataFrame'>
Chris Rock
<class 'pandas.core.frame.DataFrame'>
Chris Shadley
<class 'pandas.core.frame.DataFrame'>
Chris Stokes
<class 'pandas.core.frame.DataFrame'>
Chris Wedge
<class 'pandas.core.frame.DataFrame'>
Chris Weitz
<class 'pandas.core.frame.DataFrame'>
Christian Alvart
<class 'pandas.core.frame.DataFrame'>
Christian Carion
<class 'pandas.core.frame.DataFrame'>
Christian Ditter
<class 'pandas.core.frame.DataFrame'>
Christian Duguay
<class 'pandas.core.frame.DataFrame'>
Christian E. Christiansen
<class 'pandas.core.frame.DataFrame'>
Christian Sesma
<class 'pandas.core.frame.DataFrame'>
Christian Volckman
<class 'pandas.core.frame.DataFrame'>
Christine Jeffs
<class 'pandas.core.frame.DataFrame'>
Christophe Ali
<class 'pandas.core.frame.DataFrame'>
Christophe Barratier
<class 'pandas.core.frame.DataFrame'>
Christophe Gans
<class 'pandas.core.frame.DataFrame'>
Christopher Barnard
<class 'pandas.core.frame.DataFrame'>
Christopher Cain
<class 'pandas.core.frame.DataFrame'>
Christopher Erskin
<class 'pandas.core.frame.DataFrame'>
Christopher Guest
<class 'pandas.core.frame.DataFrame'>
Christopher Hutson
<class 'pandas.core.frame.DataFrame'>
Christopher Landon
<class 'pandas.core.frame.DataFrame'>
Christopher Leitch
<class 'pandas.core.frame.DataFrame'>
Christopher M. Bessette
<class 'pandas.core.frame.DataFrame'>
Christopher McQuarrie
<class 'pandas.core.frame.DataFrame'>
Christopher Morris
<class 'pandas.core.frame.DataFrame'>
Christopher Nolan
<class 'pandas.core.frame.DataFrame'>
Christopher Scott Cherot
<class 'pandas.core.frame.DataFrame'>
Christopher Smith
<class 'pandas.core.frame.DataFrame'>
Christopher Spencer
<class 'pandas.core.frame.DataFrame'>
Chuan Lu
<class 'pandas.core.frame.DataFrame'>
Chuck Bowman
<class 'pandas.core.frame.DataFrame'>
Chuck Russell
<class 'pandas.core.frame.DataFrame'>
Chuck Sheetz
<class 'pandas.core.frame.DataFrame'>
Ciarán Foy
<class 'pandas.core.frame.DataFrame'>
Clare Kilner
<class 'pandas.core.frame.DataFrame'>
Clark Baker
<class 'pandas.core.frame.DataFrame'>
Clark Gregg
<class 'pandas.core.frame.DataFrame'>
Clark Johnson
<class 'pandas.core.frame.DataFrame'>
Claude Chabrol
<class 'pandas.core.frame.DataFrame'>
Claude Miller
<class 'pandas.core.frame.DataFrame'>
Claudia Llosa
<class 'pandas.core.frame.DataFrame'>
Claudia Sainte-Luce
<class 'pandas.core.frame.DataFrame'>
Clay Kaytis
<class 'pandas.core.frame.DataFrame'>
Clint Eastwood
<class 'pandas.core.frame.DataFrame'>
Clive Barker
<class 'pandas.core.frame.DataFrame'>
Cody Cameron
<class 'pandas.core.frame.DataFrame'>
Colin Higgins
<class 'pandas.core.frame.DataFrame'>
Colin Minihan
<class 'pandas.core.frame.DataFrame'>
Colin Strause
<class 'pandas.core.frame.DataFrame'>
Colin Trevorrow
<class 'pandas.core.frame.DataFrame'>
Collin Joseph Neal
<class 'pandas.core.frame.DataFrame'>
Collin Schiffli
<class 'pandas.core.frame.DataFrame'>
Conor McMahon
<class 'pandas.core.frame.DataFrame'>
Conor McPherson
<class 'pandas.core.frame.DataFrame'>
Corbin Bernsen
<class 'pandas.core.frame.DataFrame'>
Corey Grant
<class 'pandas.core.frame.DataFrame'>
Corey Yuen
<class 'pandas.core.frame.DataFrame'>
Cory Edwards
<class 'pandas.core.frame.DataFrame'>
Costa-Gavras
<class 'pandas.core.frame.DataFrame'>
Courtney Hunt
<class 'pandas.core.frame.DataFrame'>
Courtney Solomon
<class 'pandas.core.frame.DataFrame'>
Craig Bolotin
<class 'pandas.core.frame.DataFrame'>
Craig Brewer
<class 'pandas.core.frame.DataFrame'>
Craig Gillespie
<class 'pandas.core.frame.DataFrame'>
Craig Johnson
<class 'pandas.core.frame.DataFrame'>
Craig Mazin
<class 'pandas.core.frame.DataFrame'>
Craig Moss
<class 'pandas.core.frame.DataFrame'>
Craig R. Baxley
<class 'pandas.core.frame.DataFrame'>
Craig Zobel
<class 'pandas.core.frame.DataFrame'>
Cristian Mungiu
<class 'pandas.core.frame.DataFrame'>
Curtis Hanson
<class 'pandas.core.frame.DataFrame'>
Cyrus Nowrasteh
<class 'pandas.core.frame.DataFrame'>
Cédric Klapisch
<class 'pandas.core.frame.DataFrame'>
D. Stevens
<class 'pandas.core.frame.DataFrame'>
D.J. Caruso
<class 'pandas.core.frame.DataFrame'>
D.W. Griffith
<class 'pandas.core.frame.DataFrame'>
DJ Pooh
<class 'pandas.core.frame.DataFrame'>
Dagur Kári
<class 'pandas.core.frame.DataFrame'>
Daisy von Scherler Mayer
<class 'pandas.core.frame.DataFrame'>
Damian Nieman
<class 'pandas.core.frame.DataFrame'>
Damien Chazelle
<class 'pandas.core.frame.DataFrame'>
Damien Dante Wayans
<class 'pandas.core.frame.DataFrame'>
Damien O'Donnell
<class 'pandas.core.frame.DataFrame'>
Damir Catic
<class 'pandas.core.frame.DataFrame'>
Damon Santostefano
<class 'pandas.core.frame.DataFrame'>
Dan Curtis
<class 'pandas.core.frame.DataFrame'>
Dan Cutforth
<class 'pandas.core.frame.DataFrame'>
Dan Fogelman
<class 'pandas.core.frame.DataFrame'>
Dan Gilroy
<class 'pandas.core.frame.DataFrame'>
Dan Harris
<class 'pandas.core.frame.DataFrame'>
Dan Ireland
<class 'pandas.core.frame.DataFrame'>
Dan Mazer
<class 'pandas.core.frame.DataFrame'>
Dan O'Bannon
<class 'pandas.core.frame.DataFrame'>
Dan Perri
<class 'pandas.core.frame.DataFrame'>
Dan Reed
<class 'pandas.core.frame.DataFrame'>
Dan Rush
<class 'pandas.core.frame.DataFrame'>
Dan Scanlon
<class 'pandas.core.frame.DataFrame'>
Dan Trachtenberg
<class 'pandas.core.frame.DataFrame'>
Dan Zukovic
<class 'pandas.core.frame.DataFrame'>
Daniel Algrant
<class 'pandas.core.frame.DataFrame'>
Daniel Barber
<class 'pandas.core.frame.DataFrame'>
Daniel Barnz
<class 'pandas.core.frame.DataFrame'>
Daniel Columbie
<class 'pandas.core.frame.DataFrame'>
Daniel Davila
<class 'pandas.core.frame.DataFrame'>
Daniel Espinosa
<class 'pandas.core.frame.DataFrame'>
Daniel Hsia
<class 'pandas.core.frame.DataFrame'>
Daniel Lee
<class 'pandas.core.frame.DataFrame'>
Daniel Mellitz
<class 'pandas.core.frame.DataFrame'>
Daniel Myrick
<class 'pandas.core.frame.DataFrame'>
Daniel Petrie Jr.
<class 'pandas.core.frame.DataFrame'>
Daniel Sackheim
<class 'pandas.core.frame.DataFrame'>
Daniel Schechter
<class 'pandas.core.frame.DataFrame'>
Daniel Stamm
<class 'pandas.core.frame.DataFrame'>
Daniel Taplitz
<class 'pandas.core.frame.DataFrame'>
Daniele Luchetti
<class 'pandas.core.frame.DataFrame'>
Danny Boyle
<class 'pandas.core.frame.DataFrame'>
Danny Cannon
<class 'pandas.core.frame.DataFrame'>
Danny DeVito
<class 'pandas.core.frame.DataFrame'>
Danny Leiner
<class 'pandas.core.frame.DataFrame'>
Danny Pang
<class 'pandas.core.frame.DataFrame'>
Danny Perez
<class 'pandas.core.frame.DataFrame'>
Danny Provenzano
<class 'pandas.core.frame.DataFrame'>
Danny Steinmann
<class 'pandas.core.frame.DataFrame'>
Dany Boon
<class 'pandas.core.frame.DataFrame'>
Darin Scott
<class 'pandas.core.frame.DataFrame'>
Dario Argento
<class 'pandas.core.frame.DataFrame'>
Darnell Martin
<class 'pandas.core.frame.DataFrame'>
Darrell Roodt
<class 'pandas.core.frame.DataFrame'>
Darren Aronofsky
<class 'pandas.core.frame.DataFrame'>
Darren Grant
<class 'pandas.core.frame.DataFrame'>
Darren Lynn Bousman
<class 'pandas.core.frame.DataFrame'>
Darren Stein
<class 'pandas.core.frame.DataFrame'>
Daryl Wein
<class 'pandas.core.frame.DataFrame'>
Daston Kalili
<class 'pandas.core.frame.DataFrame'>
Dave Borthwick
<class 'pandas.core.frame.DataFrame'>
Dave Carroll
<class 'pandas.core.frame.DataFrame'>
Dave Green
<class 'pandas.core.frame.DataFrame'>
Dave McKean
<class 'pandas.core.frame.DataFrame'>
Dave Meyers
<class 'pandas.core.frame.DataFrame'>
Dave Payne
<class 'pandas.core.frame.DataFrame'>
Dave Rodriguez
<class 'pandas.core.frame.DataFrame'>
David Anspaugh
<class 'pandas.core.frame.DataFrame'>
David Atkins
<class 'pandas.core.frame.DataFrame'>
David Ayer
<class 'pandas.core.frame.DataFrame'>
David Bowers
<class 'pandas.core.frame.DataFrame'>
David Boyd
<class 'pandas.core.frame.DataFrame'>
David Caffrey
<class 'pandas.core.frame.DataFrame'>
David Carson
<class 'pandas.core.frame.DataFrame'>
David Cronenberg
<class 'pandas.core.frame.DataFrame'>
David Cross
<class 'pandas.core.frame.DataFrame'>
David DeCoteau
<class 'pandas.core.frame.DataFrame'>
David Dobkin
<class 'pandas.core.frame.DataFrame'>
David Duchovny
<class 'pandas.core.frame.DataFrame'>
David E. Talbert
<class 'pandas.core.frame.DataFrame'>
David F. Sandberg
<class 'pandas.core.frame.DataFrame'>
David Fincher
<class 'pandas.core.frame.DataFrame'>
David Frankel
<class 'pandas.core.frame.DataFrame'>
David G. Evans
<class 'pandas.core.frame.DataFrame'>
David Gelb
<class 'pandas.core.frame.DataFrame'>
David Gordon Green
<class 'pandas.core.frame.DataFrame'>
David Hackl
<class 'pandas.core.frame.DataFrame'>
David Hayter
<class 'pandas.core.frame.DataFrame'>
David Hewlett
<class 'pandas.core.frame.DataFrame'>
David Hunt
<class 'pandas.core.frame.DataFrame'>
David Jacobson
<class 'pandas.core.frame.DataFrame'>
David Kellogg
<class 'pandas.core.frame.DataFrame'>
David Koepp
<class 'pandas.core.frame.DataFrame'>
David LaChapelle
<class 'pandas.core.frame.DataFrame'>
David Lam
<class 'pandas.core.frame.DataFrame'>
David Lean
<class 'pandas.core.frame.DataFrame'>
David Leland
<class 'pandas.core.frame.DataFrame'>
David Lowery
<class 'pandas.core.frame.DataFrame'>
David Lynch
<class 'pandas.core.frame.DataFrame'>
David M. Matthews
<class 'pandas.core.frame.DataFrame'>
David Mamet
<class 'pandas.core.frame.DataFrame'>
David McNally
<class 'pandas.core.frame.DataFrame'>
David Mirkin
<class 'pandas.core.frame.DataFrame'>
David Moreau
<class 'pandas.core.frame.DataFrame'>
David Nixon
<class 'pandas.core.frame.DataFrame'>
David Nutter
<class 'pandas.core.frame.DataFrame'>
David O. Russell
<class 'pandas.core.frame.DataFrame'>
David Oelhoffen
<class 'pandas.core.frame.DataFrame'>
David Palmer
<class 'pandas.core.frame.DataFrame'>
David Pastor
<class 'pandas.core.frame.DataFrame'>
David R. Ellis
<class 'pandas.core.frame.DataFrame'>
David Ray
<class 'pandas.core.frame.DataFrame'>
David Raynr
<class 'pandas.core.frame.DataFrame'>
David Robert Mitchell
<class 'pandas.core.frame.DataFrame'>
David S. Goyer
<class 'pandas.core.frame.DataFrame'>
David S. Ward
<class 'pandas.core.frame.DataFrame'>
David Schwimmer
<class 'pandas.core.frame.DataFrame'>
David Silverman
<class 'pandas.core.frame.DataFrame'>
David Sington
<class 'pandas.core.frame.DataFrame'>
David Slade
<class 'pandas.core.frame.DataFrame'>
David Soren
<class 'pandas.core.frame.DataFrame'>
David Twohy
<class 'pandas.core.frame.DataFrame'>
David Wain
<class 'pandas.core.frame.DataFrame'>
David Webb Peoples
<class 'pandas.core.frame.DataFrame'>
David Winning
<class 'pandas.core.frame.DataFrame'>
David Winters
<class 'pandas.core.frame.DataFrame'>
David Worth
<class 'pandas.core.frame.DataFrame'>
David Yates
<class 'pandas.core.frame.DataFrame'>
David Zucker
<class 'pandas.core.frame.DataFrame'>
Davis Guggenheim
<class 'pandas.core.frame.DataFrame'>
Dean DeBlois
<class 'pandas.core.frame.DataFrame'>
Dean Israelite
<class 'pandas.core.frame.DataFrame'>
Dean Parisot
<class 'pandas.core.frame.DataFrame'>
Dean Wright
<class 'pandas.core.frame.DataFrame'>
Deb Hagan
<class 'pandas.core.frame.DataFrame'>
Deborah Anderson
<class 'pandas.core.frame.DataFrame'>
Debra Granik
<class 'pandas.core.frame.DataFrame'>
Deepa Mehta
<class 'pandas.core.frame.DataFrame'>
Demian Lichtenstein

<class 'pandas.core.frame.DataFrame'>
James Cameron
<class 'pandas.core.frame.DataFrame'>
James Cox
<class 'pandas.core.frame.DataFrame'>
James David Pasternak
<class 'pandas.core.frame.DataFrame'>
James DeMonaco
<class 'pandas.core.frame.DataFrame'>
James Dodson
<class 'pandas.core.frame.DataFrame'>
James Fargo
<class 'pandas.core.frame.DataFrame'>
James Foley
<class 'pandas.core.frame.DataFrame'>
James Frawley
<class 'pandas.core.frame.DataFrame'>
James Gartner
<class 'pandas.core.frame.DataFrame'>
James Gray
<class 'pandas.core.frame.DataFrame'>
James Gunn
<class 'pandas.core.frame.DataFrame'>
James Isaac
<class 'pandas.core.frame.DataFrame'>
James Ivory
<class 'pandas.core.frame.DataFrame'>
James Kerwin
<class 'pandas.core.frame.DataFrame'>
James L. Brooks
<class 'pandas.core.frame.DataFrame'>
James Manera
<class 'pandas.core.frame.DataFrame'>
James Mangold
<class 'pandas.core.frame.DataFrame'>
James Marsh
<class 'pandas.core.frame.DataFrame'>
James Mather
<class 'pandas.core.frame.DataFrame'>
James McTeigue
<class 'pandas.core.frame.DataFrame'>
James Melkonian
<class 'pandas.core.frame.DataFrame'>
James Mottern
<class 'pandas.core.frame.DataFrame'>
James Nunn
<class 'pandas.core.frame.DataFrame'>
James O'Brien
<class 'pandas.core.frame.DataFrame'>
James Ponsoldt
<class 'pandas.core.frame.DataFrame'>
James Schamus
<class 'pandas.core.frame.DataFrame'>
James Toback
<class 'pandas.core.frame.DataFrame'>
James Wan
<class 'pandas.core.frame.DataFrame'>
James Watkins
<class 'pandas.core.frame.DataFrame'>
James Wong
<class 'pandas.core.frame.DataFrame'>
Jamie Babbit
<class 'pandas.core.frame.DataFrame'>
Jamie Blanks
<class 'pandas.core.frame.DataFrame'>
Jamie Thraves
<class 'pandas.core.frame.DataFrame'>
Jamie Travis
<class 'pandas.core.frame.DataFrame'>
Jamin Winans
<class 'pandas.core.frame.DataFrame'>
Jan de Bont
<class 'pandas.core.frame.DataFrame'>
Jane Campion
<class 'pandas.core.frame.DataFrame'>
Jane Clark
<class 'pandas.core.frame.DataFrame'>
Janusz Kaminski
<class 'pandas.core.frame.DataFrame'>
Jared Hess
<class 'pandas.core.frame.DataFrame'>
Jason Alexander
<class 'pandas.core.frame.DataFrame'>
Jason Bateman
<class 'pandas.core.frame.DataFrame'>
Jason Connery
<class 'pandas.core.frame.DataFrame'>
Jason Eisener
<class 'pandas.core.frame.DataFrame'>
Jason Friedberg
<class 'pandas.core.frame.DataFrame'>
Jason Miller
<class 'pandas.core.frame.DataFrame'>
Jason Moore
<class 'pandas.core.frame.DataFrame'>
Jason Naumann
<class 'pandas.core.frame.DataFrame'>
Jason Reitman
<class 'pandas.core.frame.DataFrame'>
Jason Stone
<class 'pandas.core.frame.DataFrame'>
Jason Trost
<class 'pandas.core.frame.DataFrame'>
Jason Zada
<class 'pandas.core.frame.DataFrame'>
Jaume Balagueró
<class 'pandas.core.frame.DataFrame'>
Jaume Collet-Serra
<class 'pandas.core.frame.DataFrame'>
Jay Alaimo
<class 'pandas.core.frame.DataFrame'>
Jay Chandrasekhar
<class 'pandas.core.frame.DataFrame'>
Jay Duplass
<class 'pandas.core.frame.DataFrame'>
Jay Levey
<class 'pandas.core.frame.DataFrame'>
Jay Oliva
<class 'pandas.core.frame.DataFrame'>
Jay Roach
<class 'pandas.core.frame.DataFrame'>
Jay Russell
<class 'pandas.core.frame.DataFrame'>
Je-kyu Kang
<class 'pandas.core.frame.DataFrame'>
Jean-François Richet
<class 'pandas.core.frame.DataFrame'>
Jean-Jacques Annaud
<class 'pandas.core.frame.DataFrame'>
Jean-Jacques Mantello
<class 'pandas.core.frame.DataFrame'>
Jean-Luc Godard
<class 'pandas.core.frame.DataFrame'>
Jean-Marc Vallée
<class 'pandas.core.frame.DataFrame'>
Jean-Marie Poiré
<class 'pandas.core.frame.DataFrame'>
Jean-Paul Rappeneau
<class 'pandas.core.frame.DataFrame'>
Jean-Pierre Jeunet
<class 'pandas.core.frame.DataFrame'>
Jeannot Szwarc
<class 'pandas.core.frame.DataFrame'>
Jeb Stuart
<class 'pandas.core.frame.DataFrame'>
Jee-woon Kim
<class 'pandas.core.frame.DataFrame'>
Jeff Burr
<class 'pandas.core.frame.DataFrame'>
Jeff Crook
<class 'pandas.core.frame.DataFrame'>
Jeff Franklin
<class 'pandas.core.frame.DataFrame'>
Jeff Garlin
<class 'pandas.core.frame.DataFrame'>
Jeff Kanew
<class 'pandas.core.frame.DataFrame'>
Jeff Lowell
<class 'pandas.core.frame.DataFrame'>
Jeff Nathanson
<class 'pandas.core.frame.DataFrame'>
Jeff Nichols
<class 'pandas.core.frame.DataFrame'>
Jeff Schaffer
<class 'pandas.core.frame.DataFrame'>
Jeff Tremaine
<class 'pandas.core.frame.DataFrame'>
Jeff Wadlow
<class 'pandas.core.frame.DataFrame'>
Jeffrey St. Jules
<class 'pandas.core.frame.DataFrame'>
Jeffrey W. Byrd
<class 'pandas.core.frame.DataFrame'>
Jehane Noujaim
<class 'pandas.core.frame.DataFrame'>
Jem Cohen
<class 'pandas.core.frame.DataFrame'>
Jennifer Finnigan
<class 'pandas.core.frame.DataFrame'>
Jennifer Flackett
<class 'pandas.core.frame.DataFrame'>
Jennifer Wynne Farmer
<class 'pandas.core.frame.DataFrame'>
Jennifer Yuh Nelson
<class 'pandas.core.frame.DataFrame'>
Jeremy Brock
<class 'pandas.core.frame.DataFrame'>
Jeremy Degruson
<class 'pandas.core.frame.DataFrame'>
Jeremy Leven
<class 'pandas.core.frame.DataFrame'>
Jeremy Saulnier
<class 'pandas.core.frame.DataFrame'>
Jeremy Sims
<class 'pandas.core.frame.DataFrame'>
Jerome Elston Scott
<class 'pandas.core.frame.DataFrame'>
Jerome Robbins
<class 'pandas.core.frame.DataFrame'>
Jerry Belson
<class 'pandas.core.frame.DataFrame'>
Jerry Dugan
<class 'pandas.core.frame.DataFrame'>
Jerry Jameson
<class 'pandas.core.frame.DataFrame'>
Jerry Rees
<class 'pandas.core.frame.DataFrame'>
Jerry Zaks
<class 'pandas.core.frame.DataFrame'>
Jerry Zucker
<class 'pandas.core.frame.DataFrame'>
Jesse Dylan
<class 'pandas.core.frame.DataFrame'>
Jesse Peretz
<class 'pandas.core.frame.DataFrame'>
Jesse Vaughan
<class 'pandas.core.frame.DataFrame'>
Jessica Bendinger
<class 'pandas.core.frame.DataFrame'>
Jessie Nelson
<class 'pandas.core.frame.DataFrame'>
Jessy Terrero
<class 'pandas.core.frame.DataFrame'>
Jeta Amata
<class 'pandas.core.frame.DataFrame'>
Jez Butterworth
<class 'pandas.core.frame.DataFrame'>
Jill Sprecher
<class 'pandas.core.frame.DataFrame'>
Jim Abrahams
<class 'pandas.core.frame.DataFrame'>
Jim Amatulli
<class 'pandas.core.frame.DataFrame'>
Jim Chuchu
<class 'pandas.core.frame.DataFrame'>
Jim Fall
<class 'pandas.core.frame.DataFrame'>
Jim Field Smith
<class 'pandas.core.frame.DataFrame'>
Jim Gillespie
<class 'pandas.core.frame.DataFrame'>
Jim Goddard
<class 'pandas.core.frame.DataFrame'>
Jim Hanon
<class 'pandas.core.frame.DataFrame'>
Jim Issa
<class 'pandas.core.frame.DataFrame'>
Jim Jarmusch
<class 'pandas.core.frame.DataFrame'>
Jim Mickle
<class 'pandas.core.frame.DataFrame'>
Jim Sheridan
<class 'pandas.core.frame.DataFrame'>
Jim Sonzero
<class 'pandas.core.frame.DataFrame'>
Jimmy Hayward
<class 'pandas.core.frame.DataFrame'>
Jirí Menzel
<class 'pandas.core.frame.DataFrame'>
Joachim Rønning
<class 'pandas.core.frame.DataFrame'>
Joan Chen
<class 'pandas.core.frame.DataFrame'>
Joby Harold
<class 'pandas.core.frame.DataFrame'>
Jodie Foster
<class 'pandas.core.frame.DataFrame'>
Jody Hill
<class 'pandas.core.frame.DataFrame'>
Joe Berlinger
<class 'pandas.core.frame.DataFrame'>
Joe Camp
<class 'pandas.core.frame.DataFrame'>
Joe Carnahan
<class 'pandas.core.frame.DataFrame'>
Joe Chappelle
<class 'pandas.core.frame.DataFrame'>
Joe Charbanic
<class 'pandas.core.frame.DataFrame'>
Joe Cornish
<class 'pandas.core.frame.DataFrame'>
Joe Cross
<class 'pandas.core.frame.DataFrame'>
Joe Dante
<class 'pandas.core.frame.DataFrame'>
Joe Johnston
<class 'pandas.core.frame.DataFrame'>
Joe Kenemore
<class 'pandas.core.frame.DataFrame'>
Joe Marino
<class 'pandas.core.frame.DataFrame'>
Joe Nussbaum
<class 'pandas.core.frame.DataFrame'>
Joe Pytka
<class 'pandas.core.frame.DataFrame'>
Joe Roth
<class 'pandas.core.frame.DataFrame'>
Joe Swanberg
<class 'pandas.core.frame.DataFrame'>
Joe Wright
<class 'pandas.core.frame.DataFrame'>
Joel Anderson
<class 'pandas.core.frame.DataFrame'>
Joel Coen
<class 'pandas.core.frame.DataFrame'>
Joel Edgerton
<class 'pandas.core.frame.DataFrame'>
Joel Gallen
<class 'pandas.core.frame.DataFrame'>
Joel Paul Reisig
<class 'pandas.core.frame.DataFrame'>
Joel Schumacher
<class 'pandas.core.frame.DataFrame'>
Joel Zwick
<class 'pandas.core.frame.DataFrame'>
Joey Lauren Adams
<class 'pandas.core.frame.DataFrame'>
Johanna Schwartz
<class 'pandas.core.frame.DataFrame'>
John 'Bud' Cardos
<class 'pandas.core.frame.DataFrame'>
John A. Davis
<class 'pandas.core.frame.DataFrame'>
John Badham
<class 'pandas.core.frame.DataFrame'>
John Blanchard
<class 'pandas.core.frame.DataFrame'>
John Bonito
<class 'pandas.core.frame.DataFrame'>
John Boorman
<class 'pandas.core.frame.DataFrame'>
John Cameron Mitchell
<class 'pandas.core.frame.DataFrame'>
John Carl Buechler
<class 'pandas.core.frame.DataFrame'>
John Carney
<class 'pandas.core.frame.DataFrame'>
John Carpenter
<class 'pandas.core.frame.DataFrame'>
John Cornell
<class 'pandas.core.frame.DataFrame'>
John Cromwell
<class 'pandas.core.frame.DataFrame'>
John Crowley
<class 'pandas.core.frame.DataFrame'>
John Curran
<class 'pandas.core.frame.DataFrame'>
John D. Hancock
<class 'pandas.core.frame.DataFrame'>
John Dahl
<class 'pandas.core.frame.DataFrame'>
John Duigan
<class 'pandas.core.frame.DataFrame'>
John Eng
<class 'pandas.core.frame.DataFrame'>
John Erick Dowdle
<class 'pandas.core.frame.DataFrame'>
John Ford
<class 'pandas.core.frame.DataFrame'>
John Fortenberry
<class 'pandas.core.frame.DataFrame'>
John Francis Daley
<class 'pandas.core.frame.DataFrame'>
John Frankenheimer
<class 'pandas.core.frame.DataFrame'>
John G. Avildsen
<class 'pandas.core.frame.DataFrame'>
John Gatins
<class 'pandas.core.frame.DataFrame'>
John Glen
<class 'pandas.core.frame.DataFrame'>
John Gray
<class 'pandas.core.frame.DataFrame'>
John Guillermin
<class 'pandas.core.frame.DataFrame'>
John Gulager
<class 'pandas.core.frame.DataFrame'>
John H. Lee
<class 'pandas.core.frame.DataFrame'>
John Hamburg
<class 'pandas.core.frame.DataFrame'>
John Herzfeld
<class 'pandas.core.frame.DataFrame'>
John Hillcoat
<class 'pandas.core.frame.DataFrame'>
John Hoffman
<class 'pandas.core.frame.DataFrame'>
John Huston
<class 'pandas.core.frame.DataFrame'>
John Lafia
<class 'pandas.core.frame.DataFrame'>
John Laing
<class 'pandas.core.frame.DataFrame'>
John Landis
<class 'pandas.core.frame.DataFrame'>
John Lasseter
<class 'pandas.core.frame.DataFrame'>
John Lee Hancock
<class 'pandas.core.frame.DataFrame'>
John Luessenhop
<class 'pandas.core.frame.DataFrame'>
John Maclean
<class 'pandas.core.frame.DataFrame'>
John Madden
<class 'pandas.core.frame.DataFrame'>
John Maybury
<class 'pandas.core.frame.DataFrame'>
John McNaughton
<class 'pandas.core.frame.DataFrame'>
John McTiernan
<class 'pandas.core.frame.DataFrame'>
John Michael McDonagh
<class 'pandas.core.frame.DataFrame'>
John Milius
<class 'pandas.core.frame.DataFrame'>
John Moore
<class 'pandas.core.frame.DataFrame'>
John Murlowski
<class 'pandas.core.frame.DataFrame'>
John Ottman
<class 'pandas.core.frame.DataFrame'>
John Pasquin
<class 'pandas.core.frame.DataFrame'>
John Patrick Shanley
<class 'pandas.core.frame.DataFrame'>
John Polson
<class 'pandas.core.frame.DataFrame'>
John Putch
<class 'pandas.core.frame.DataFrame'>
John R. Leonetti
<class 'pandas.core.frame.DataFrame'>
John Reinhardt
<class 'pandas.core.frame.DataFrame'>
John Sayles
<class 'pandas.core.frame.DataFrame'>
John Schlesinger
<class 'pandas.core.frame.DataFrame'>
John Schultz
<class 'pandas.core.frame.DataFrame'>
John Simpson
<class 'pandas.core.frame.DataFrame'>
John Singleton
<class 'pandas.core.frame.DataFrame'>
John Stainton
<class 'pandas.core.frame.DataFrame'>
John Stephenson
<class 'pandas.core.frame.DataFrame'>
John Stockwell
<class 'pandas.core.frame.DataFrame'>
John Sturges
<class 'pandas.core.frame.DataFrame'>
John Turturro
<class 'pandas.core.frame.DataFrame'>
John Waters
<class 'pandas.core.frame.DataFrame'>
John Wells
<class 'pandas.core.frame.DataFrame'>
John Whitesell
<class 'pandas.core.frame.DataFrame'>
John Woo
<class 'pandas.core.frame.DataFrame'>
Johnnie To
<class 'pandas.core.frame.DataFrame'>
Johnny Remo
<class 'pandas.core.frame.DataFrame'>
Jon Amiel
<class 'pandas.core.frame.DataFrame'>
Jon Avnet
<class 'pandas.core.frame.DataFrame'>
Jon Cassar
<class 'pandas.core.frame.DataFrame'>
Jon Favreau
<class 'pandas.core.frame.DataFrame'>
Jon Gunn
<class 'pandas.core.frame.DataFrame'>
Jon Hess
<class 'pandas.core.frame.DataFrame'>
Jon Hurwitz
<class 'pandas.core.frame.DataFrame'>
Jon Kasdan
<class 'pandas.core.frame.DataFrame'>
Jon Knautz
<class 'pandas.core.frame.DataFrame'>
Jon Lucas
<class 'pandas.core.frame.DataFrame'>
Jon M. Chu
<class 'pandas.core.frame.DataFrame'>
Jon Poll
<class 'pandas.core.frame.DataFrame'>
Jon Shear
<class 'pandas.core.frame.DataFrame'>
Jon Stewart
<class 'pandas.core.frame.DataFrame'>
Jon Turteltaub
<class 'pandas.core.frame.DataFrame'>
Jon Wright
<class 'pandas.core.frame.DataFrame'>
Jonas Elmer
<class 'pandas.core.frame.DataFrame'>
Jonas Åkerlund
<class 'pandas.core.frame.DataFrame'>
Jonathan Caouette
<class 'pandas.core.frame.DataFrame'>
Jonathan Dayton
<class 'pandas.core.frame.DataFrame'>
Jonathan Demme
<class 'pandas.core.frame.DataFrame'>
Jonathan English
<class 'pandas.core.frame.DataFrame'>
Jonathan Frakes
<class 'pandas.core.frame.DataFrame'>
Jonathan Glazer
<class 'pandas.core.frame.DataFrame'>
Jonathan Hensleigh
<class 'pandas.core.frame.DataFrame'>
Jonathan Jakubowicz
<class 'pandas.core.frame.DataFrame'>
Jonathan Kaplan
<class 'pandas.core.frame.DataFrame'>
Jonathan Kesselman
<class 'pandas.core.frame.DataFrame'>
Jonathan Levine
<class 'pandas.core.frame.DataFrame'>
Jonathan Liebesman
<class 'pandas.core.frame.DataFrame'>
Jonathan Lynn
<class 'pandas.core.frame.DataFrame'>
Jonathan Meyers
<class 'pandas.core.frame.DataFrame'>
Jonathan Mostow
<class 'pandas.core.frame.DataFrame'>
Jonathan Newman
<class 'pandas.core.frame.DataFrame'>
Jonathan Parker
<class 'pandas.core.frame.DataFrame'>
Jonathan Teplitzky
<class 'pandas.core.frame.DataFrame'>
Jonathan Wacks
<class 'pandas.core.frame.DataFrame'>
Joon-ho Bong
<class 'pandas.core.frame.DataFrame'>
Jorge Blanco
<class 'pandas.core.frame.DataFrame'>
Jorge Gaggero
<class 'pandas.core.frame.DataFrame'>
Jorge R. Gutiérrez
<class 'pandas.core.frame.DataFrame'>
Jorge Ramírez Suárez
<class 'pandas.core.frame.DataFrame'>
Jorma Taccone
<class 'pandas.core.frame.DataFrame'>
Josef Rusnak
<class 'pandas.core.frame.DataFrame'>
Joseph Dorman
<class 'pandas.core.frame.DataFrame'>
Joseph Gordon-Levitt
<class 'pandas.core.frame.DataFrame'>
Joseph Green
<class 'pandas.core.frame.DataFrame'>
Joseph Kahn
<class 'pandas.core.frame.DataFrame'>
Joseph Kosinski
<class 'pandas.core.frame.DataFrame'>
Joseph L. Mankiewicz
<class 'pandas.core.frame.DataFrame'>
Joseph Mazzella
<class 'pandas.core.frame.DataFrame'>
Joseph Ruben
<class 'pandas.core.frame.DataFrame'>
Joseph Sargent
<class 'pandas.core.frame.DataFrame'>
Joseph Zito
<class 'pandas.core.frame.DataFrame'>
Josh Boone
<class 'pandas.core.frame.DataFrame'>
Josh Gordon
<class 'pandas.core.frame.DataFrame'>
Josh Schwartz
<class 'pandas.core.frame.DataFrame'>
Josh Trank
<class 'pandas.core.frame.DataFrame'>
Joshua Logan
<class 'pandas.core.frame.DataFrame'>
Joshua Marston
<class 'pandas.core.frame.DataFrame'>
Joshua Michael Stern
<class 'pandas.core.frame.DataFrame'>
Joshua Oppenheimer
<class 'pandas.core.frame.DataFrame'>
Joshua Seftel
<class 'pandas.core.frame.DataFrame'>
Joshua Tickell
<class 'pandas.core.frame.DataFrame'>
Joss Whedon
<class 'pandas.core.frame.DataFrame'>
José Luis Valenzuela
<class 'pandas.core.frame.DataFrame'>
José Padilha
<class 'pandas.core.frame.DataFrame'>
Juan Carlos Fresnadillo
<class 'pandas.core.frame.DataFrame'>
Juan José Campanella
<class 'pandas.core.frame.DataFrame'>
Judd Apatow
<class 'pandas.core.frame.DataFrame'>
Jugal Hansraj
<class 'pandas.core.frame.DataFrame'>
Julian Gilbey
<class 'pandas.core.frame.DataFrame'>
Julian Jarrold
<class 'pandas.core.frame.DataFrame'>
Julian Schnabel
<class 'pandas.core.frame.DataFrame'>
Julie Anne Robinson
<class 'pandas.core.frame.DataFrame'>
Julie Davis
<class 'pandas.core.frame.DataFrame'>
Julie Taymor
<class 'pandas.core.frame.DataFrame'>
Julien Temple
<class 'pandas.core.frame.DataFrame'>
Julio DePietro
<class 'pandas.core.frame.DataFrame'>
Jun Falkenstein
<class 'pandas.core.frame.DataFrame'>
Juraj Jakubisko
<class 'pandas.core.frame.DataFrame'>
Justin Chadwick
<class 'pandas.core.frame.DataFrame'>
Justin Dillon
<class 'pandas.core.frame.DataFrame'>
Justin Kerrigan
<class 'pandas.core.frame.DataFrame'>
Justin Lin
<class 'pandas.core.frame.DataFrame'>
Justin Molotnikov
<class 'pandas.core.frame.DataFrame'>
Justin Paul Miller
<class 'pandas.core.frame.DataFrame'>
Justin Thomas Ostensen
<class 'pandas.core.frame.DataFrame'>
Justin Tipping
<class 'pandas.core.frame.DataFrame'>
Justin Zackham
<class 'pandas.core.frame.DataFrame'>
Jérôme Deschamps
<class 'pandas.core.frame.DataFrame'>
Jérôme Salle
<class 'pandas.core.frame.DataFrame'>
K. King
<class 'pandas.core.frame.DataFrame'>
Kabir Sadanand
<class 'pandas.core.frame.DataFrame'>
Kaige Chen
<class 'pandas.core.frame.DataFrame'>
Kar-Wai Wong
<class 'pandas.core.frame.DataFrame'>
Karan Johar
<class 'pandas.core.frame.DataFrame'>
Karen Moncrieff
<class 'pandas.core.frame.DataFrame'>
Karey Kirkpatrick
<class 'pandas.core.frame.DataFrame'>
Kari Skogland
<class 'pandas.core.frame.DataFrame'>
Karim Aïnouz
<class 'pandas.core.frame.DataFrame'>
Karyn Kusama
<class 'pandas.core.frame.DataFrame'>
Kasi Lemmons
<class 'pandas.core.frame.DataFrame'>
Kat Coiro
<class 'pandas.core.frame.DataFrame'>
Kate Barker-Froyland
<class 'pandas.core.frame.DataFrame'>
Kate Connor
<class 'pandas.core.frame.DataFrame'>
Katherine Brooks
<class 'pandas.core.frame.DataFrame'>
Katherine Dieckmann
<class 'pandas.core.frame.DataFrame'>
Kathryn Bigelow
<class 'pandas.core.frame.DataFrame'>
Katie Aselton
<class 'pandas.core.frame.DataFrame'>
Katja von Garnier
<class 'pandas.core.frame.DataFrame'>
Katsuhiro Ôtomo
<class 'pandas.core.frame.DataFrame'>
Katt Shea
<class 'pandas.core.frame.DataFrame'>
Kay Pollak
<class 'pandas.core.frame.DataFrame'>
Keenen Ivory Wayans
<class 'pandas.core.frame.DataFrame'>
Keith Gordon
<class 'pandas.core.frame.DataFrame'>
Keith Parmer
<class 'pandas.core.frame.DataFrame'>
Kelly Asbury
<class 'pandas.core.frame.DataFrame'>
Kelly Makin
<class 'pandas.core.frame.DataFrame'>
Kelly Reichardt
<class 'pandas.core.frame.DataFrame'>
Ken Annakin
<class 'pandas.core.frame.DataFrame'>
Ken Del Conte
<class 'pandas.core.frame.DataFrame'>
Ken Kwapis
<class 'pandas.core.frame.DataFrame'>
Ken Loach
<class 'pandas.core.frame.DataFrame'>
Ken Roht
<class 'pandas.core.frame.DataFrame'>
Ken Scott
<class 'pandas.core.frame.DataFrame'>
Ken Shapiro
<class 'pandas.core.frame.DataFrame'>
Kenneth Branagh
<class 'pandas.core.frame.DataFrame'>
Kenneth Johnson
<class 'pandas.core.frame.DataFrame'>
Kenneth Lonergan
<class 'pandas.core.frame.DataFrame'>
Kenny Ortega
<class 'pandas.core.frame.DataFrame'>
Kent Alterman
<class 'pandas.core.frame.DataFrame'>
Kerry Conran
<class 'pandas.core.frame.DataFrame'>
Kevin Allen
<class 'pandas.core.frame.DataFrame'>
Kevin Bray
<class 'pandas.core.frame.DataFrame'>
Kevin Brodie
<class 'pandas.core.frame.DataFrame'>
Kevin Carraway
<class 'pandas.core.frame.DataFrame'>
Kevin Costner
<class 'pandas.core.frame.DataFrame'>
Kevin Donovan
<class 'pandas.core.frame.DataFrame'>
Kevin Greutert
<class 'pandas.core.frame.DataFrame'>
Kevin Hamedani
<class 'pandas.core.frame.DataFrame'>
Kevin Hooks
<class 'pandas.core.frame.DataFrame'>
Kevin Jordan
<class 'pandas.core.frame.DataFrame'>
Kevin Lima
<class 'pandas.core.frame.DataFrame'>
Kevin Macdonald
<class 'pandas.core.frame.DataFrame'>
Kevin Munroe
<class 'pandas.core.frame.DataFrame'>
Kevin Reynolds
<class 'pandas.core.frame.DataFrame'>
Kevin Rodney Sullivan
<class 'pandas.core.frame.DataFrame'>
Kevin Smith
<class 'pandas.core.frame.DataFrame'>
Kevin Spacey
<class 'pandas.core.frame.DataFrame'>
Kevin Tancharoen
<class 'pandas.core.frame.DataFrame'>
Kevin Tenney
<class 'pandas.core.frame.DataFrame'>

<class 'pandas.core.frame.DataFrame'>
Michael Herz
<class 'pandas.core.frame.DataFrame'>
Michael Hoffman
<class 'pandas.core.frame.DataFrame'>
Michael Hoffman Jr.
<class 'pandas.core.frame.DataFrame'>
Michael J. Bassett
<class 'pandas.core.frame.DataFrame'>
Michael Jai White
<class 'pandas.core.frame.DataFrame'>
Michael Kang
<class 'pandas.core.frame.DataFrame'>
Michael Landon Jr.
<class 'pandas.core.frame.DataFrame'>
Michael Lehmann
<class 'pandas.core.frame.DataFrame'>
Michael Lembeck
<class 'pandas.core.frame.DataFrame'>
Michael Mann
<class 'pandas.core.frame.DataFrame'>
Michael Martin
<class 'pandas.core.frame.DataFrame'>
Michael Mayer
<class 'pandas.core.frame.DataFrame'>
Michael McCullers
<class 'pandas.core.frame.DataFrame'>
Michael McGowan
<class 'pandas.core.frame.DataFrame'>
Michael Meredith
<class 'pandas.core.frame.DataFrame'>
Michael Moore
<class 'pandas.core.frame.DataFrame'>
Michael O. Sajbel
<class 'pandas.core.frame.DataFrame'>
Michael Patrick Jann
<class 'pandas.core.frame.DataFrame'>
Michael Patrick King
<class 'pandas.core.frame.DataFrame'>
Michael Polish
<class 'pandas.core.frame.DataFrame'>
Michael Pressman
<class 'pandas.core.frame.DataFrame'>
Michael Radford
<class 'pandas.core.frame.DataFrame'>
Michael Ritchie
<class 'pandas.core.frame.DataFrame'>
Michael Roemer
<class 'pandas.core.frame.DataFrame'>
Michael Rymer
<class 'pandas.core.frame.DataFrame'>
Michael Schultz
<class 'pandas.core.frame.DataFrame'>
Michael Spierig
<class 'pandas.core.frame.DataFrame'>
Michael Sucsy
<class 'pandas.core.frame.DataFrame'>
Michael Taliferro
<class 'pandas.core.frame.DataFrame'>
Michael Tiddes
<class 'pandas.core.frame.DataFrame'>
Michael Tollin
<class 'pandas.core.frame.DataFrame'>
Michael Wadleigh
<class 'pandas.core.frame.DataFrame'>
Michael Walker
<class 'pandas.core.frame.DataFrame'>
Michael Winner
<class 'pandas.core.frame.DataFrame'>
Michael Winnick
<class 'pandas.core.frame.DataFrame'>
Michael Winterbottom
<class 'pandas.core.frame.DataFrame'>
Michel Gondry
<class 'pandas.core.frame.DataFrame'>
Michel Hazanavicius
<class 'pandas.core.frame.DataFrame'>
Michel Leclerc
<class 'pandas.core.frame.DataFrame'>
Michel Orion Scott
<class 'pandas.core.frame.DataFrame'>
Mick Jackson
<class 'pandas.core.frame.DataFrame'>
Mickey Liddell
<class 'pandas.core.frame.DataFrame'>
Miguel Arteta
<class 'pandas.core.frame.DataFrame'>
Miguel Sapochnik
<class 'pandas.core.frame.DataFrame'>
Mikael Håfström
<class 'pandas.core.frame.DataFrame'>
Mikael Salomon
<class 'pandas.core.frame.DataFrame'>
Mike Barker
<class 'pandas.core.frame.DataFrame'>
Mike Bigelow
<class 'pandas.core.frame.DataFrame'>
Mike Binder
<class 'pandas.core.frame.DataFrame'>
Mike Bruce
<class 'pandas.core.frame.DataFrame'>
Mike Cahill
<class 'pandas.core.frame.DataFrame'>
Mike Disa
<class 'pandas.core.frame.DataFrame'>
Mike Figgis
<class 'pandas.core.frame.DataFrame'>
Mike Flanagan
<class 'pandas.core.frame.DataFrame'>
Mike Gabriel
<class 'pandas.core.frame.DataFrame'>
Mike Hodges
<class 'pandas.core.frame.DataFrame'>
Mike Judge
<class 'pandas.core.frame.DataFrame'>
Mike Leigh
<class 'pandas.core.frame.DataFrame'>
Mike Marvin
<class 'pandas.core.frame.DataFrame'>
Mike Mayhall
<class 'pandas.core.frame.DataFrame'>
Mike McCoy
<class 'pandas.core.frame.DataFrame'>
Mike Mills
<class 'pandas.core.frame.DataFrame'>
Mike Mitchell
<class 'pandas.core.frame.DataFrame'>
Mike Nawrocki
<class 'pandas.core.frame.DataFrame'>
Mike Newell
<class 'pandas.core.frame.DataFrame'>
Mike Nichols
<class 'pandas.core.frame.DataFrame'>
Mike van Diem
<class 'pandas.core.frame.DataFrame'>
Mikel Rueda
<class 'pandas.core.frame.DataFrame'>
Milos Forman
<class 'pandas.core.frame.DataFrame'>
Mimi Leder
<class 'pandas.core.frame.DataFrame'>
Mira Nair
<class 'pandas.core.frame.DataFrame'>
Miranda July
<class 'pandas.core.frame.DataFrame'>
Mitch Davis
<class 'pandas.core.frame.DataFrame'>
Mitchell Altieri
<class 'pandas.core.frame.DataFrame'>
Mitchell Lichtenstein
<class 'pandas.core.frame.DataFrame'>
Molly Bernstein
<class 'pandas.core.frame.DataFrame'>
Mona Fastvold
<class 'pandas.core.frame.DataFrame'>
Monte Hellman
<class 'pandas.core.frame.DataFrame'>
Mor Loushy
<class 'pandas.core.frame.DataFrame'>
Mora Stephens
<class 'pandas.core.frame.DataFrame'>
Morgan J. Freeman
<class 'pandas.core.frame.DataFrame'>
Morgan Neville
<class 'pandas.core.frame.DataFrame'>
Morgan Spurlock
<class 'pandas.core.frame.DataFrame'>
Mort Nathan
<class 'pandas.core.frame.DataFrame'>
Morten Tyldum
<class 'pandas.core.frame.DataFrame'>
Moustapha Akkad
<class 'pandas.core.frame.DataFrame'>
Myles Berkowitz
<class 'pandas.core.frame.DataFrame'>
Måns Mårlind
<class 'pandas.core.frame.DataFrame'>
Nacho Vigalondo
<class 'pandas.core.frame.DataFrame'>
Nadia Tass
<class 'pandas.core.frame.DataFrame'>
Nadine Labaki
<class 'pandas.core.frame.DataFrame'>
Nae Caranfil
<class 'pandas.core.frame.DataFrame'>
Nancy Meyers
<class 'pandas.core.frame.DataFrame'>
Nancy Walker
<class 'pandas.core.frame.DataFrame'>
Nanette Burstein
<class 'pandas.core.frame.DataFrame'>
Nat Faxon
<class 'pandas.core.frame.DataFrame'>
Natalie Bible'
<class 'pandas.core.frame.DataFrame'>
Nate Parker
<class 'pandas.core.frame.DataFrame'>
Nathan Frankowski
<class 'pandas.core.frame.DataFrame'>
Nathan Greno
<class 'pandas.core.frame.DataFrame'>
Nathan Smith Jones
<class 'pandas.core.frame.DataFrame'>
Neal Brennan
<class 'pandas.core.frame.DataFrame'>
Neema Barnette
<class 'pandas.core.frame.DataFrame'>
Neil Burger
<class 'pandas.core.frame.DataFrame'>
Neil Jordan
<class 'pandas.core.frame.DataFrame'>
Neil LaBute
<class 'pandas.core.frame.DataFrame'>
Neil Marshall
<class 'pandas.core.frame.DataFrame'>
Neil Mcenery-West
<class 'pandas.core.frame.DataFrame'>
Neill Blomkamp
<class 'pandas.core.frame.DataFrame'>
Neill Dela Llana
<class 'pandas.core.frame.DataFrame'>
Nelson McCormick
<class 'pandas.core.frame.DataFrame'>
Newt Arnold
<class 'pandas.core.frame.DataFrame'>
Niall Johnson
<class 'pandas.core.frame.DataFrame'>
Nicholas Fackler
<class 'pandas.core.frame.DataFrame'>
Nicholas Hytner
<class 'pandas.core.frame.DataFrame'>
Nicholas Jarecki
<class 'pandas.core.frame.DataFrame'>
Nicholas Meyer
<class 'pandas.core.frame.DataFrame'>
Nicholas Ray
<class 'pandas.core.frame.DataFrame'>
Nicholas Stoller
<class 'pandas.core.frame.DataFrame'>
Nicholaus Goossen
<class 'pandas.core.frame.DataFrame'>
Nick Cassavetes
<class 'pandas.core.frame.DataFrame'>
Nick Gomez
<class 'pandas.core.frame.DataFrame'>
Nick Hamm
<class 'pandas.core.frame.DataFrame'>
Nick Hurran
<class 'pandas.core.frame.DataFrame'>
Nick Love
<class 'pandas.core.frame.DataFrame'>
Nick Murphy
<class 'pandas.core.frame.DataFrame'>
Nick Tomnay
<class 'pandas.core.frame.DataFrame'>
Nickolas Perry
<class 'pandas.core.frame.DataFrame'>
Nicolae Constantin Tanase
<class 'pandas.core.frame.DataFrame'>
Nicolas Winding Refn
<class 'pandas.core.frame.DataFrame'>
Nicole Holofcener
<class 'pandas.core.frame.DataFrame'>
Niels Arden Oplev
<class 'pandas.core.frame.DataFrame'>
Nigel Cole
<class 'pandas.core.frame.DataFrame'>
Niki Caro
<class 'pandas.core.frame.DataFrame'>
Nils Gaup
<class 'pandas.core.frame.DataFrame'>
Nima Nourizadeh
<class 'pandas.core.frame.DataFrame'>
Nimród Antal
<class 'pandas.core.frame.DataFrame'>
Nnegest Likké
<class 'pandas.core.frame.DataFrame'>
Noah Baumbach
<class 'pandas.core.frame.DataFrame'>
Noah Buschel
<class 'pandas.core.frame.DataFrame'>
Noam Murro
<class 'pandas.core.frame.DataFrame'>
Noel Marshall
<class 'pandas.core.frame.DataFrame'>
Nora Ephron
<class 'pandas.core.frame.DataFrame'>
Norman Ferguson
<class 'pandas.core.frame.DataFrame'>
Norman Jewison
<class 'pandas.core.frame.DataFrame'>
Ol Parker
<class 'pandas.core.frame.DataFrame'>
Olatunde Osunsanmi
<class 'pandas.core.frame.DataFrame'>
Ole Bornedal
<class 'pandas.core.frame.DataFrame'>
Ole Christian Madsen
<class 'pandas.core.frame.DataFrame'>
Oleg Stepchenko
<class 'pandas.core.frame.DataFrame'>
Oliver Blackburn
<class 'pandas.core.frame.DataFrame'>
Oliver Hirschbiegel
<class 'pandas.core.frame.DataFrame'>
Oliver Parker
<class 'pandas.core.frame.DataFrame'>
Oliver Stone
<class 'pandas.core.frame.DataFrame'>
Olivier Assayas
<class 'pandas.core.frame.DataFrame'>
Olivier Dahan
<class 'pandas.core.frame.DataFrame'>
Olivier Megaton
<class 'pandas.core.frame.DataFrame'>
Oren Moverman
<class 'pandas.core.frame.DataFrame'>
Oren Peli
<class 'pandas.core.frame.DataFrame'>
Orson Welles
<class 'pandas.core.frame.DataFrame'>
Ossie Davis
<class 'pandas.core.frame.DataFrame'>
P.J. Hogan
<class 'pandas.core.frame.DataFrame'>
Pan Nalin
<class 'pandas.core.frame.DataFrame'>
Panos Cosmatos
<class 'pandas.core.frame.DataFrame'>
Paolo Monico
<class 'pandas.core.frame.DataFrame'>
Paolo Sorrentino
<class 'pandas.core.frame.DataFrame'>
Pascal Arnold
<class 'pandas.core.frame.DataFrame'>
Pascal Chaumeil
<class 'pandas.core.frame.DataFrame'>
Pat Holden
<class 'pandas.core.frame.DataFrame'>
Pat O'Connor
<class 'pandas.core.frame.DataFrame'>
Patrice Leconte
<class 'pandas.core.frame.DataFrame'>
Patricia Cardoso
<class 'pandas.core.frame.DataFrame'>
Patricia Riggen
<class 'pandas.core.frame.DataFrame'>
Patricia Rozema
<class 'pandas.core.frame.DataFrame'>
Patrick Creadon
<class 'pandas.core.frame.DataFrame'>
Patrick Gilles
<class 'pandas.core.frame.DataFrame'>
Patrick Gilmore
<class 'pandas.core.frame.DataFrame'>
Patrick Hughes
<class 'pandas.core.frame.DataFrame'>
Patrick Lussier
<class 'pandas.core.frame.DataFrame'>
Patrick Meaney
<class 'pandas.core.frame.DataFrame'>
Patrick Read Johnson
<class 'pandas.core.frame.DataFrame'>
Patrick Ryan Sims
<class 'pandas.core.frame.DataFrame'>
Patrick Stettner
<class 'pandas.core.frame.DataFrame'>
Patrick Tatopoulos
<class 'pandas.core.frame.DataFrame'>
Patty Jenkins
<class 'pandas.core.frame.DataFrame'>
Paul Abascal
<class 'pandas.core.frame.DataFrame'>
Paul Andrew Williams
<class 'pandas.core.frame.DataFrame'>
Paul Bartel
<class 'pandas.core.frame.DataFrame'>
Paul Bolger
<class 'pandas.core.frame.DataFrame'>
Paul Bunnell
<class 'pandas.core.frame.DataFrame'>
Paul Crowder
<class 'pandas.core.frame.DataFrame'>
Paul Donovan
<class 'pandas.core.frame.DataFrame'>
Paul Feig
<class 'pandas.core.frame.DataFrame'>
Paul Fierlinger
<class 'pandas.core.frame.DataFrame'>
Paul Fox
<class 'pandas.core.frame.DataFrame'>
Paul Greengrass
<class 'pandas.core.frame.DataFrame'>
Paul Gross
<class 'pandas.core.frame.DataFrame'>
Paul Haggis
<class 'pandas.core.frame.DataFrame'>
Paul Hunter
<class 'pandas.core.frame.DataFrame'>
Paul King
<class 'pandas.core.frame.DataFrame'>
Paul Mazursky
<class 'pandas.core.frame.DataFrame'>
Paul McGuigan
<class 'pandas.core.frame.DataFrame'>
Paul Michael Glaser
<class 'pandas.core.frame.DataFrame'>
Paul Schrader
<class 'pandas.core.frame.DataFrame'>
Paul Thomas Anderson
<class 'pandas.core.frame.DataFrame'>
Paul Tibbitt
<class 'pandas.core.frame.DataFrame'>
Paul Verhoeven
<class 'pandas.core.frame.DataFrame'>
Paul W.S. Anderson
<class 'pandas.core.frame.DataFrame'>
Paul Weiland
<class 'pandas.core.frame.DataFrame'>
Paul Weitz
<class 'pandas.core.frame.DataFrame'>
Pawel Pawlikowski
<class 'pandas.core.frame.DataFrame'>
Pece Dingo
<class 'pandas.core.frame.DataFrame'>
Pedro Almodóvar
<class 'pandas.core.frame.DataFrame'>
Penelope Spheeris
<class 'pandas.core.frame.DataFrame'>
Penny Marshall
<class 'pandas.core.frame.DataFrame'>
Perry Andelin Blake
<class 'pandas.core.frame.DataFrame'>
Perry Lang
<class 'pandas.core.frame.DataFrame'>
Pete Docter
<class 'pandas.core.frame.DataFrame'>
Pete Jones
<class 'pandas.core.frame.DataFrame'>
Pete Travis
<class 'pandas.core.frame.DataFrame'>
Peter Atencio
<class 'pandas.core.frame.DataFrame'>
Peter Berg
<class 'pandas.core.frame.DataFrame'>
Peter Billingsley
<class 'pandas.core.frame.DataFrame'>
Peter Care
<class 'pandas.core.frame.DataFrame'>
Peter Cattaneo
<class 'pandas.core.frame.DataFrame'>
Peter Chelsom
<class 'pandas.core.frame.DataFrame'>
Peter Cousens
<class 'pandas.core.frame.DataFrame'>
Peter DeLuise
<class 'pandas.core.frame.DataFrame'>
Peter Faiman
<class 'pandas.core.frame.DataFrame'>
Peter Farrelly
<class 'pandas.core.frame.DataFrame'>
Peter Flinth
<class 'pandas.core.frame.DataFrame'>
Peter H. Hunt
<class 'pandas.core.frame.DataFrame'>
Peter Hastings
<class 'pandas.core.frame.DataFrame'>
Peter Hedges
<class 'pandas.core.frame.DataFrame'>
Peter Hewitt
<class 'pandas.core.frame.DataFrame'>
Peter Ho-Sun Chan
<class 'pandas.core.frame.DataFrame'>
Peter Howitt
<class 'pandas.core.frame.DataFrame'>
Peter Hyams
<class 'pandas.core.frame.DataFrame'>
Peter Jackson
<class 'pandas.core.frame.DataFrame'>
Peter Kassovitz
<class 'pandas.core.frame.DataFrame'>
Peter Kosminsky
<class 'pandas.core.frame.DataFrame'>
Peter Landesman
<class 'pandas.core.frame.DataFrame'>
Peter Lepeniotis
<class 'pandas.core.frame.DataFrame'>
Peter Lord
<class 'pandas.core.frame.DataFrame'>
Peter M. Cohen
<class 'pandas.core.frame.DataFrame'>
Peter MacDonald
<class 'pandas.core.frame.DataFrame'>
Peter Medak
<class 'pandas.core.frame.DataFrame'>
Peter R. Hunt
<class 'pandas.core.frame.DataFrame'>
Peter Ramsey
<class 'pandas.core.frame.DataFrame'>
Peter Segal
<class 'pandas.core.frame.DataFrame'>
Peter Sohn
<class 'pandas.core.frame.DataFrame'>
Peter Sollett
<class 'pandas.core.frame.DataFrame'>
Peter Stebbings
<class 'pandas.core.frame.DataFrame'>
Peter Webber
<class 'pandas.core.frame.DataFrame'>
Peter Weir
<class 'pandas.core.frame.DataFrame'>
Peter Yates
<class 'pandas.core.frame.DataFrame'>
Petter Næss
<class 'pandas.core.frame.DataFrame'>
Peyton Reed
<class 'pandas.core.frame.DataFrame'>
Phil Alden Robinson
<class 'pandas.core.frame.DataFrame'>
Phil Claydon
<class 'pandas.core.frame.DataFrame'>
Phil Joanou
<class 'pandas.core.frame.DataFrame'>
Phil Lord
<class 'pandas.core.frame.DataFrame'>
Phil Morrison
<class 'pandas.core.frame.DataFrame'>
Phil Traill
<class 'pandas.core.frame.DataFrame'>
Philip G. Atwell
<class 'pandas.core.frame.DataFrame'>
Philip Kaufman
<class 'pandas.core.frame.DataFrame'>
Philip Saville
<class 'pandas.core.frame.DataFrame'>
Philip Zlotorynski
<class 'pandas.core.frame.DataFrame'>
Phillip Noyce
<class 'pandas.core.frame.DataFrame'>
Phyllida Lloyd
<class 'pandas.core.frame.DataFrame'>
Pierre Coffin
<class 'pandas.core.frame.DataFrame'>
Pierre Morel
<class 'pandas.core.frame.DataFrame'>
Pitof
<class 'pandas.core.frame.DataFrame'>
Piyush Dinker Pandya
<class 'pandas.core.frame.DataFrame'>
Pou-Soi Cheang
<class 'pandas.core.frame.DataFrame'>
Prachya Pinkaew
<class 'pandas.core.frame.DataFrame'>
Preston A. Whitmore II
<class 'pandas.core.frame.DataFrame'>
Qasim Basir
<class 'pandas.core.frame.DataFrame'>
Quentin Dupieux
<class 'pandas.core.frame.DataFrame'>
Quentin Tarantino
<class 'pandas.core.frame.DataFrame'>
R. Balki
<class 'pandas.core.frame.DataFrame'>
R.J. Cutler
<class 'pandas.core.frame.DataFrame'>
RZA
<class 'pandas.core.frame.DataFrame'>
Rachel Goldenberg
<class 'pandas.core.frame.DataFrame'>
Rachel Perkins
<class 'pandas.core.frame.DataFrame'>
Rachel Talalay
<class 'pandas.core.frame.DataFrame'>
Rafa Lara
<class 'pandas.core.frame.DataFrame'>
Raja Gosnell
<class 'pandas.core.frame.DataFrame'>
Raja Menon
<class 'pandas.core.frame.DataFrame'>
Rajkumar Hirani
<class 'pandas.core.frame.DataFrame'>
Rakesh Roshan
<class 'pandas.core.frame.DataFrame'>
Rakeysh Omprakash Mehra
<class 'pandas.core.frame.DataFrame'>
Ralph Fiennes
<class 'pandas.core.frame.DataFrame'>
Ralph Nelson
<class 'pandas.core.frame.DataFrame'>
Ralph Ziman
<class 'pandas.core.frame.DataFrame'>
Ramaa Mosley
<class 'pandas.core.frame.DataFrame'>
Rand Ravich
<class 'pandas.core.frame.DataFrame'>
Randal Kleiser
<class 'pandas.core.frame.DataFrame'>
Randall Miller
<class 'pandas.core.frame.DataFrame'>
Randall Rubin
<class 'pandas.core.frame.DataFrame'>
Randall Wallace
<class 'pandas.core.frame.DataFrame'>
Randy Moore
<class 'pandas.core.frame.DataFrame'>
Rania Attieh
<class 'pandas.core.frame.DataFrame'>
Rawson Marshall Thurber
<class 'pandas.core.frame.DataFrame'>
Ray Griggs
<class 'pandas.core.frame.DataFrame'>
Ray Lawrence
<class 'pandas.core.frame.DataFrame'>
Raymond De Felitta
<class 'pandas.core.frame.DataFrame'>
Rebecca Miller
<class 'pandas.core.frame.DataFrame'>
Reed Cowan
<class 'pandas.core.frame.DataFrame'>
Regardt van den Bergh
<class 'pandas.core.frame.DataFrame'>
Reginald Hudlin
<class 'pandas.core.frame.DataFrame'>
Reinhard Klooss
<class 'pandas.core.frame.DataFrame'>
Remo
<class 'pandas.core.frame.DataFrame'>
Renny Harlin
<class 'pandas.core.frame.DataFrame'>
René Féret
<class 'pandas.core.frame.DataFrame'>
Rian Johnson
<class 'pandas.core.frame.DataFrame'>
Ric Roman Waugh
<class 'pandas.core.frame.DataFrame'>
Rich Christiano
<class 'pandas.core.frame.DataFrame'>
Rich Cowan
<class 'pandas.core.frame.DataFrame'>
Rich Moore
<class 'pandas.core.frame.DataFrame'>
Richard Attenborough
<class 'pandas.core.frame.DataFrame'>
Richard Ayoade
<class 'pandas.core.frame.DataFrame'>
Richard Benjamin
<class 'pandas.core.frame.DataFrame'>
Richard Boddington
<class 'pandas.core.frame.DataFrame'>
Richard Brooks
<class 'pandas.core.frame.DataFrame'>
Richard Curtis
<class 'pandas.core.frame.DataFrame'>
Richard Donner
<class 'pandas.core.frame.DataFrame'>
Richard Dutcher
<class 'pandas.core.frame.DataFrame'>
Richard E. Grant
<class 'pandas.core.frame.DataFrame'>
Richard Eyre
<class 'pandas.core.frame.DataFrame'>
Richard Fleischer
<class 'pandas.core.frame.DataFrame'>
Richard Glatzer
<class 'pandas.core.frame.DataFrame'>
Richard J. Lewis
<class 'pandas.core.frame.DataFrame'>
Richard Kelly
<class 'pandas.core.frame.DataFrame'>
Richard Kwietniowski
<class 'pandas.core.frame.DataFrame'>
Richard LaGravenese
<class 'pandas.core.frame.DataFrame'>
Richard Lester
<class 'pandas.core.frame.DataFrame'>
Richard Linklater
<class 'pandas.core.frame.DataFrame'>
Richard Loncraine
<class 'pandas.core.frame.DataFrame'>
Richard Marquand
<class 'pandas.core.frame.DataFrame'>
Richard Montoya
<class 'pandas.core.frame.DataFrame'>
Richard Raymond
<class 'pandas.core.frame.DataFrame'>
Richard Rich
<class 'pandas.core.frame.DataFrame'>
Richard Schenkman
<class 'pandas.core.frame.DataFrame'>
Richard Shepard
<class 'pandas.core.frame.DataFrame'>
Richard Wallace
<class 'pandas.core.frame.DataFrame'>
Richard Williams
<class 'pandas.core.frame.DataFrame'>
Rick Bieber
<class 'pandas.core.frame.DataFrame'>
Rick Famuyiwa
<class 'pandas.core.frame.DataFrame'>
Rick Friedberg
<class 'pandas.core.frame.DataFrame'>
Rick Rosenthal
<class 'pandas.core.frame.DataFrame'>
Rick de Oliveira
<class 'pandas.core.frame.DataFrame'>
Ricki Stern
<class 'pandas.core.frame.DataFrame'>
Ricky Gervais
<class 'pandas.core.frame.DataFrame'>
Ridley Scott
<class 'pandas.core.frame.DataFrame'>
Ringo Lam
<class 'pandas.core.frame.DataFrame'>
Risa Bramon Garcia
<class 'pandas.core.frame.DataFrame'>
Rita Merson
<class 'pandas.core.frame.DataFrame'>
Ritesh Batra
<class 'pandas.core.frame.DataFrame'>
Rob Bowman
<class 'pandas.core.frame.DataFrame'>
Rob Cohen
<class 'pandas.core.frame.DataFrame'>
Rob Hawk
<class 'pandas.core.frame.DataFrame'>
Rob Hedden
<class 'pandas.core.frame.DataFrame'>
Rob Letterman
<class 'pandas.core.frame.DataFrame'>
Rob Marshall
<class 'pandas.core.frame.DataFrame'>
Rob McKittrick
<class 'pandas.core.frame.DataFrame'>
Rob Minkoff
<class 'pandas.core.frame.DataFrame'>
Rob Pritts
<class 'pandas.core.frame.DataFrame'>
Rob Reiner
<class 'pandas.core.frame.DataFrame'>
Rob Schmidt
<class 'pandas.core.frame.DataFrame'>
Rob Zombie
<class 'pandas.core.frame.DataFrame'>
Robby Henson
<class 'pandas.core.frame.DataFrame'>
Robert Adetuyi
<class 'pandas.core.frame.DataFrame'>
Robert Altman
<class 'pandas.core.frame.DataFrame'>
Robert B. Weide
<class 'pandas.core.frame.DataFrame'>
Robert Ben Garant
<class 'pandas.core.frame.DataFrame'>
Robert Bennett
<class 'pandas.core.frame.DataFrame'>
Robert Butler
<class 'pandas.core.frame.DataFrame'>
Robert C. Cooper
<class 'pandas.core.frame.DataFrame'>
Robert Cary
<class 'pandas.core.frame.DataFrame'>

<class 'pandas.core.frame.DataFrame'>
William Bindley
<class 'pandas.core.frame.DataFrame'>
William Brent Bell
<class 'pandas.core.frame.DataFrame'>
William Cottrell
<class 'pandas.core.frame.DataFrame'>
William Dear
<class 'pandas.core.frame.DataFrame'>
William Eubank
<class 'pandas.core.frame.DataFrame'>
William Friedkin
<class 'pandas.core.frame.DataFrame'>
William Gazecki
<class 'pandas.core.frame.DataFrame'>
William H. Macy
<class 'pandas.core.frame.DataFrame'>
William Kaufman
<class 'pandas.core.frame.DataFrame'>
William Malone
<class 'pandas.core.frame.DataFrame'>
William Phillips
<class 'pandas.core.frame.DataFrame'>
William Sachs
<class 'pandas.core.frame.DataFrame'>
William Shatner
<class 'pandas.core.frame.DataFrame'>
William Wyler
<class 'pandas.core.frame.DataFrame'>
Wilson Yip
<class 'pandas.core.frame.DataFrame'>
Wolfgang Becker
<class 'pandas.core.frame.DataFrame'>
Wolfgang Petersen
<class 'pandas.core.frame.DataFrame'>
Woo-Suk Kang
<class 'pandas.core.frame.DataFrame'>
Woody Allen
<class 'pandas.core.frame.DataFrame'>
Wych Kaosayananda
<class 'pandas.core.frame.DataFrame'>
Xavier Beauvois
<class 'pandas.core.frame.DataFrame'>
Xavier Gens
<class 'pandas.core.frame.DataFrame'>
Yarrow Cheney
<class 'pandas.core.frame.DataFrame'>
Yash Chopra
<class 'pandas.core.frame.DataFrame'>
Yimou Zhang
<class 'pandas.core.frame.DataFrame'>
Yorgos Lanthimos
<class 'pandas.core.frame.DataFrame'>
Youssef Delara
<class 'pandas.core.frame.DataFrame'>
Yuefeng Song
<class 'pandas.core.frame.DataFrame'>
Zach Braff
<class 'pandas.core.frame.DataFrame'>
Zach Cregger
<class 'pandas.core.frame.DataFrame'>
Zack Snyder
<class 'pandas.core.frame.DataFrame'>
Zack Ward
<class 'pandas.core.frame.DataFrame'>
Zackary Adler
<class 'pandas.core.frame.DataFrame'>
Zak Penn
<class 'pandas.core.frame.DataFrame'>
Zal Batmanglij
<class 'pandas.core.frame.DataFrame'>
Zoran Lisinac
<class 'pandas.core.frame.DataFrame'>
Álex de la Iglesia
<class 'pandas.core.frame.DataFrame'>
Émile Gaudreault
<class 'pandas.core.frame.DataFrame'>
Éric Tessier
<class 'pandas.core.frame.DataFrame'>
Étienne Faure
<class 'pandas.core.frame.DataFrame'>

In [25]:
# 分组的统计计算
# 分组计算每一个统计函数都是作用在每个group上

grouped.mean() #每个数值型数据在每个组中的平均值

grouped.sum()

grouped.std()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>num_critic_for_reviews</th>
      <th>duration</th>
      <th>director_facebook_likes</th>
      <th>actor_3_facebook_likes</th>
      <th>actor_1_facebook_likes</th>
      <th>gross</th>
      <th>num_voted_users</th>
      <th>cast_total_facebook_likes</th>
      <th>facenumber_in_poster</th>
      <th>num_user_for_reviews</th>
      <th>budget</th>
      <th>title_year</th>
      <th>actor_2_facebook_likes</th>
      <th>imdb_score</th>
      <th>aspect_ratio</th>
      <th>movie_facebook_likes</th>
    </tr>
    <tr>
      <th>director_name</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>A. Raven Cruz</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Aaron Hann</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Aaron Schneider</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Aaron Seltzer</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Abel Ferrara</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam Brooks</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam Carolla</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam Goldberg</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam Green</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam Jay Epstein</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam Marcus</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam McKay</th>
      <td>99.710414</td>
      <td>16.277797</td>
      <td>0.0</td>
      <td>3379.133419</td>
      <td>255574.385780</td>
      <td>4.990008e+07</td>
      <td>51935.543477</td>
      <td>258094.921447</td>
      <td>1.505545</td>
      <td>107.318995</td>
      <td>2.835489e+07</td>
      <td>4.179314</td>
      <td>7713.624310</td>
      <td>0.526941</td>
      <td>0.204124</td>
      <td>39196.938656</td>
    </tr>
    <tr>
      <th>Adam Rapp</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam Rifkin</th>
      <td>26.870058</td>
      <td>0.000000</td>
      <td>0.0</td>
      <td>195.868578</td>
      <td>374.059487</td>
      <td>NaN</td>
      <td>21638.174611</td>
      <td>1281.984594</td>
      <td>0.000000</td>
      <td>136.471609</td>
      <td>1.042983e+07</td>
      <td>11.313708</td>
      <td>539.522474</td>
      <td>0.424264</td>
      <td>NaN</td>
      <td>33.234019</td>
    </tr>
    <tr>
      <th>Adam Shankman</th>
      <td>94.272780</td>
      <td>13.987239</td>
      <td>0.0</td>
      <td>605.199480</td>
      <td>6113.328343</td>
      <td>3.677206e+07</td>
      <td>40971.586947</td>
      <td>8323.829334</td>
      <td>3.461523</td>
      <td>273.020636</td>
      <td>2.461961e+07</td>
      <td>3.583195</td>
      <td>975.196821</td>
      <td>0.752021</td>
      <td>0.000000</td>
      <td>12492.194797</td>
    </tr>
    <tr>
      <th>Adrian Lyne</th>
      <td>51.409305</td>
      <td>12.662280</td>
      <td>0.0</td>
      <td>149.703039</td>
      <td>303.748800</td>
      <td>6.373560e+07</td>
      <td>15919.860392</td>
      <td>875.284335</td>
      <td>0.000000</td>
      <td>195.531754</td>
      <td>1.995620e+07</td>
      <td>8.504901</td>
      <td>226.983847</td>
      <td>0.476095</td>
      <td>0.000000</td>
      <td>1500.000000</td>
    </tr>
    <tr>
      <th>Adrienne Shelly</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Agnieszka Holland</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Agnieszka Wojtowicz-Vosloo</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Agustín Díaz Yanes</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Aki Kaurismäki</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Akira Kurosawa</th>
      <td>90.509668</td>
      <td>48.083261</td>
      <td>0.0</td>
      <td>0.000000</td>
      <td>204.353860</td>
      <td>1.557084e+05</td>
      <td>159485.106070</td>
      <td>217.788889</td>
      <td>4.242641</td>
      <td>393.151370</td>
      <td>7.000357e+06</td>
      <td>27.577164</td>
      <td>1.414214</td>
      <td>0.848528</td>
      <td>0.339411</td>
      <td>7527.151686</td>
    </tr>
    <tr>
      <th>Akiva Goldsman</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Akiva Schaffer</th>
      <td>88.911941</td>
      <td>8.082904</td>
      <td>0.0</td>
      <td>60.335175</td>
      <td>145.492268</td>
      <td>1.179516e+07</td>
      <td>25500.984216</td>
      <td>245.375902</td>
      <td>0.577350</td>
      <td>33.486316</td>
      <td>0.000000e+00</td>
      <td>2.886751</td>
      <td>90.643992</td>
      <td>0.577350</td>
      <td>0.000000</td>
      <td>8660.254038</td>
    </tr>
    <tr>
      <th>Al Franklin</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Al Silliman Jr.</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Alain Resnais</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Alan Alda</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Alan Cohn</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Alan J. Pakula</th>
      <td>16.263456</td>
      <td>21.213203</td>
      <td>0.0</td>
      <td>738.219480</td>
      <td>4949.747468</td>
      <td>4.093504e+07</td>
      <td>9876.160413</td>
      <td>2810.749455</td>
      <td>0.000000</td>
      <td>17.677670</td>
      <td>2.899138e+07</td>
      <td>2.828427</td>
      <td>2121.320344</td>
      <td>0.282843</td>
      <td>0.000000</td>
      <td>692.257539</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>William Phillips</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>William Sachs</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>William Shatner</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>William Wyler</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Wilson Yip</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Wolfgang Becker</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Wolfgang Petersen</th>
      <td>71.697778</td>
      <td>70.698218</td>
      <td>0.0</td>
      <td>338.803989</td>
      <td>31013.216477</td>
      <td>6.855197e+07</td>
      <td>103676.277519</td>
      <td>32340.017120</td>
      <td>1.154701</td>
      <td>519.774860</td>
      <td>6.574192e+07</td>
      <td>9.551863</td>
      <td>4665.514217</td>
      <td>0.899735</td>
      <td>0.243975</td>
      <td>8323.804075</td>
    </tr>
    <tr>
      <th>Woo-Suk Kang</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Woody Allen</th>
      <td>120.898485</td>
      <td>10.788803</td>
      <td>0.0</td>
      <td>290.196590</td>
      <td>6504.684519</td>
      <td>1.394988e+07</td>
      <td>77426.845934</td>
      <td>7451.980673</td>
      <td>1.511858</td>
      <td>172.198918</td>
      <td>7.001121e+06</td>
      <td>13.441230</td>
      <td>2483.709348</td>
      <td>0.529068</td>
      <td>0.239966</td>
      <td>18015.534714</td>
    </tr>
    <tr>
      <th>Wych Kaosayananda</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Xavier Beauvois</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Xavier Gens</th>
      <td>13.435029</td>
      <td>19.798990</td>
      <td>0.0</td>
      <td>229.809704</td>
      <td>801.859090</td>
      <td>2.804776e+07</td>
      <td>77971.957655</td>
      <td>1977.070560</td>
      <td>2.121320</td>
      <td>106.066017</td>
      <td>1.484924e+07</td>
      <td>2.828427</td>
      <td>78.488853</td>
      <td>0.353553</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>Yarrow Cheney</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Yash Chopra</th>
      <td>14.849242</td>
      <td>11.313708</td>
      <td>0.0</td>
      <td>426.385389</td>
      <td>0.000000</td>
      <td>8.895474e+04</td>
      <td>5548.666912</td>
      <td>2671.449419</td>
      <td>2.828427</td>
      <td>118.086832</td>
      <td>1.538664e+05</td>
      <td>5.656854</td>
      <td>1513.208512</td>
      <td>0.707107</td>
      <td>0.000000</td>
      <td>7071.067812</td>
    </tr>
    <tr>
      <th>Yimou Zhang</th>
      <td>83.957047</td>
      <td>22.114959</td>
      <td>0.0</td>
      <td>262.755726</td>
      <td>7776.485614</td>
      <td>4.179137e+06</td>
      <td>63180.925322</td>
      <td>7860.527753</td>
      <td>1.281740</td>
      <td>351.948226</td>
      <td>3.414235e+07</td>
      <td>4.356850</td>
      <td>288.787088</td>
      <td>0.906228</td>
      <td>0.000000</td>
      <td>4530.862170</td>
    </tr>
    <tr>
      <th>Yorgos Lanthimos</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Youssef Delara</th>
      <td>0.707107</td>
      <td>5.656854</td>
      <td>0.0</td>
      <td>203.646753</td>
      <td>0.000000</td>
      <td>NaN</td>
      <td>145.663997</td>
      <td>1421.284630</td>
      <td>0.707107</td>
      <td>1.414214</td>
      <td>2.637508e+05</td>
      <td>0.707107</td>
      <td>332.340187</td>
      <td>0.353553</td>
      <td>0.000000</td>
      <td>287.085353</td>
    </tr>
    <tr>
      <th>Yuefeng Song</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Zach Braff</th>
      <td>39.597980</td>
      <td>2.828427</td>
      <td>0.0</td>
      <td>60.104076</td>
      <td>11578.873542</td>
      <td>1.640013e+07</td>
      <td>111902.476550</td>
      <td>12227.290460</td>

In [26]:
# 只针对某个或某几个特征进行计算
grouped['duration','director_facebook_likes'].sum()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>duration</th>
      <th>director_facebook_likes</th>
    </tr>
    <tr>
      <th>director_name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>A. Raven Cruz</th>
      <td>97.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Aaron Hann</th>
      <td>87.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Aaron Schneider</th>
      <td>100.0</td>
      <td>11.0</td>
    </tr>
    <tr>
      <th>Aaron Seltzer</th>
      <td>85.0</td>
      <td>64.0</td>
    </tr>
    <tr>
      <th>Abel Ferrara</th>
      <td>99.0</td>
      <td>220.0</td>
    </tr>
    <tr>
      <th>Adam Brooks</th>
      <td>112.0</td>
      <td>20.0</td>
    </tr>
    <tr>
      <th>Adam Carolla</th>
      <td>98.0</td>
      <td>102.0</td>
    </tr>
    <tr>
      <th>Adam Goldberg</th>
      <td>111.0</td>
      <td>1000.0</td>
    </tr>
    <tr>
      <th>Adam Green</th>
      <td>93.0</td>
      <td>134.0</td>
    </tr>
    <tr>
      <th>Adam Jay Epstein</th>
      <td>76.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Adam Marcus</th>
      <td>91.0</td>
      <td>18.0</td>
    </tr>
    <tr>
      <th>Adam McKay</th>
      <td>715.0</td>
      <td>1710.0</td>
    </tr>
    <tr>
      <th>Adam Rapp</th>
      <td>98.0</td>
      <td>9.0</td>
    </tr>
    <tr>
      <th>Adam Rifkin</th>
      <td>190.0</td>
      <td>178.0</td>
    </tr>
    <tr>
      <th>Adam Shankman</th>
      <td>850.0</td>
      <td>1304.0</td>
    </tr>
    <tr>
      <th>Adrian Lyne</th>
      <td>450.0</td>
      <td>852.0</td>
    </tr>
    <tr>
      <th>Adrienne Shelly</th>
      <td>108.0</td>
      <td>191.0</td>
    </tr>
    <tr>
      <th>Agnieszka Holland</th>
      <td>104.0</td>
      <td>238.0</td>
    </tr>
    <tr>
      <th>Agnieszka Wojtowicz-Vosloo</th>
      <td>104.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Agustín Díaz Yanes</th>
      <td>145.0</td>
      <td>13.0</td>
    </tr>
    <tr>
      <th>Aki Kaurismäki</th>
      <td>93.0</td>
      <td>592.0</td>
    </tr>
    <tr>
      <th>Akira Kurosawa</th>
      <td>336.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Akiva Goldsman</th>
      <td>118.0</td>
      <td>167.0</td>
    </tr>
    <tr>
      <th>Akiva Schaffer</th>
      <td>292.0</td>
      <td>246.0</td>
    </tr>
    <tr>
      <th>Al Franklin</th>
      <td>96.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Al Silliman Jr.</th>
      <td>93.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Alain Resnais</th>
      <td>104.0</td>
      <td>752.0</td>
    </tr>
    <tr>
      <th>Alan Alda</th>
      <td>107.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Alan Cohn</th>
      <td>96.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Alan J. Pakula</th>
      <td>252.0</td>
      <td>158.0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>William Phillips</th>
      <td>89.0</td>
      <td>3.0</td>
    </tr>
    <tr>
      <th>William Sachs</th>
      <td>95.0</td>
      <td>14.0</td>
    </tr>
    <tr>
      <th>William Shatner</th>
      <td>107.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>William Wyler</th>
      <td>172.0</td>
      <td>355.0</td>
    </tr>
    <tr>
      <th>Wilson Yip</th>
      <td>105.0</td>
      <td>25.0</td>
    </tr>
    <tr>
      <th>Wolfgang Becker</th>
      <td>121.0</td>
      <td>31.0</td>
    </tr>
    <tr>
      <th>Wolfgang Petersen</th>
      <td>1062.0</td>
      <td>1743.0</td>
    </tr>
    <tr>
      <th>Woo-Suk Kang</th>
      <td>135.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Woody Allen</th>
      <td>2194.0</td>
      <td>242000.0</td>
    </tr>
    <tr>
      <th>Wych Kaosayananda</th>
      <td>91.0</td>
      <td>8.0</td>
    </tr>
    <tr>
      <th>Xavier Beauvois</th>
      <td>122.0</td>
      <td>22.0</td>
    </tr>
    <tr>
      <th>Xavier Gens</th>
      <td>216.0</td>
      <td>174.0</td>
    </tr>
    <tr>
      <th>Yarrow Cheney</th>
      <td>87.0</td>
      <td>11.0</td>
    </tr>
    <tr>
      <th>Yash Chopra</th>
      <td>368.0</td>
      <td>294.0</td>
    </tr>
    <tr>
      <th>Yimou Zhang</th>
      <td>838.0</td>
      <td>4888.0</td>
    </tr>
    <tr>
      <th>Yorgos Lanthimos</th>
      <td>94.0</td>
      <td>252.0</td>
    </tr>
    <tr>
      <th>Youssef Delara</th>
      <td>168.0</td>
      <td>16.0</td>
    </tr>
    <tr>
      <th>Yuefeng Song</th>
      <td>88.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Zach Braff</th>
      <td>208.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Zach Cregger</th>
      <td>90.0</td>
      <td>138.0</td>
    </tr>
    <tr>
      <th>Zack Snyder</th>
      <td>1107.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Zack Ward</th>
      <td>92.0</td>
      <td>662.0</td>
    </tr>
    <tr>
      <th>Zackary Adler</th>
      <td>110.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Zak Penn</th>
      <td>94.0</td>
      <td>87.0</td>
    </tr>
    <tr>
      <th>Zal Batmanglij</th>
      <td>201.0</td>
      <td>258.0</td>
    </tr>
    <tr>
      <th>Zoran Lisinac</th>
      <td>108.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Álex de la Iglesia</th>
      <td>104.0</td>
      <td>275.0</td>
    </tr>
    <tr>
      <th>Émile Gaudreault</th>
      <td>92.0</td>
      <td>9.0</td>
    </tr>
    <tr>
      <th>Éric Tessier</th>
      <td>99.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Étienne Faure</th>
      <td>98.0</td>
      <td>77.0</td>
    </tr>
  </tbody>
</table>
<p>2398 rows × 2 columns</p>
</div>

In [35]:
# 对每一个数据特征都求 平均值，总和，标准差
import numpy as np
grouped.agg([np.mean, np.sum, np.std])
grouped['duration','director_facebook_likes'].agg([np.mean, np.sum, np.std])

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }

    .dataframe thead tr:last-of-type th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="3" halign="left">duration</th>
      <th colspan="3" halign="left">director_facebook_likes</th>
    </tr>
    <tr>
      <th></th>
      <th>mean</th>
      <th>sum</th>
      <th>std</th>
      <th>mean</th>
      <th>sum</th>
      <th>std</th>
    </tr>
    <tr>
      <th>director_name</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>A. Raven Cruz</th>
      <td>97.000000</td>
      <td>97.0</td>
      <td>NaN</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Aaron Hann</th>
      <td>87.000000</td>
      <td>87.0</td>
      <td>NaN</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Aaron Schneider</th>
      <td>100.000000</td>
      <td>100.0</td>
      <td>NaN</td>
      <td>11.0</td>
      <td>11.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Aaron Seltzer</th>
      <td>85.000000</td>
      <td>85.0</td>
      <td>NaN</td>
      <td>64.0</td>
      <td>64.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Abel Ferrara</th>
      <td>99.000000</td>
      <td>99.0</td>
      <td>NaN</td>
      <td>220.0</td>
      <td>220.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam Brooks</th>
      <td>112.000000</td>
      <td>112.0</td>
      <td>NaN</td>
      <td>20.0</td>
      <td>20.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam Carolla</th>
      <td>98.000000</td>
      <td>98.0</td>
      <td>NaN</td>
      <td>102.0</td>
      <td>102.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam Goldberg</th>
      <td>111.000000</td>
      <td>111.0</td>
      <td>NaN</td>
      <td>1000.0</td>
      <td>1000.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam Green</th>
      <td>93.000000</td>
      <td>93.0</td>
      <td>NaN</td>
      <td>134.0</td>
      <td>134.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam Jay Epstein</th>
      <td>76.000000</td>
      <td>76.0</td>
      <td>NaN</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam Marcus</th>
      <td>91.000000</td>
      <td>91.0</td>
      <td>NaN</td>
      <td>18.0</td>
      <td>18.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam McKay</th>
      <td>119.166667</td>
      <td>715.0</td>
      <td>16.277797</td>
      <td>285.0</td>
      <td>1710.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Adam Rapp</th>
      <td>98.000000</td>
      <td>98.0</td>
      <td>NaN</td>
      <td>9.0</td>
      <td>9.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Adam Rifkin</th>
      <td>95.000000</td>
      <td>190.0</td>
      <td>0.000000</td>
      <td>89.0</td>
      <td>178.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Adam Shankman</th>
      <td>106.250000</td>
      <td>850.0</td>
      <td>13.987239</td>
      <td>163.0</td>
      <td>1304.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Adrian Lyne</th>
      <td>112.500000</td>
      <td>450.0</td>
      <td>12.662280</td>
      <td>213.0</td>
      <td>852.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Adrienne Shelly</th>
      <td>108.000000</td>
      <td>108.0</td>
      <td>NaN</td>
      <td>191.0</td>
      <td>191.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Agnieszka Holland</th>
      <td>104.000000</td>
      <td>104.0</td>
      <td>NaN</td>
      <td>238.0</td>
      <td>238.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Agnieszka Wojtowicz-Vosloo</th>
      <td>104.000000</td>
      <td>104.0</td>
      <td>NaN</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Agustín Díaz Yanes</th>
      <td>145.000000</td>
      <td>145.0</td>
      <td>NaN</td>
      <td>13.0</td>
      <td>13.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Aki Kaurismäki</th>
      <td>93.000000</td>
      <td>93.0</td>
      <td>NaN</td>
      <td>592.0</td>
      <td>592.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Akira Kurosawa</th>
      <td>168.000000</td>
      <td>336.0</td>
      <td>48.083261</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Akiva Goldsman</th>
      <td>118.000000</td>
      <td>118.0</td>
      <td>NaN</td>
      <td>167.0</td>
      <td>167.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Akiva Schaffer</th>
      <td>97.333333</td>
      <td>292.0</td>
      <td>8.082904</td>
      <td>82.0</td>
      <td>246.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Al Franklin</th>
      <td>96.000000</td>
      <td>96.0</td>
      <td>NaN</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Al Silliman Jr.</th>
      <td>93.000000</td>
      <td>93.0</td>
      <td>NaN</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Alain Resnais</th>
      <td>104.000000</td>
      <td>104.0</td>
      <td>NaN</td>
      <td>752.0</td>
      <td>752.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Alan Alda</th>
      <td>107.000000</td>
      <td>107.0</td>
      <td>NaN</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Alan Cohn</th>
      <td>96.000000</td>
      <td>96.0</td>
      <td>NaN</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Alan J. Pakula</th>
      <td>126.000000</td>
      <td>252.0</td>
      <td>21.213203</td>
      <td>79.0</td>
      <td>158.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>William Phillips</th>
      <td>89.000000</td>
      <td>89.0</td>
      <td>NaN</td>
      <td>3.0</td>
      <td>3.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>William Sachs</th>
      <td>95.000000</td>
      <td>95.0</td>
      <td>NaN</td>
      <td>14.0</td>
      <td>14.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>William Shatner</th>
      <td>107.000000</td>
      <td>107.0</td>
      <td>NaN</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>William Wyler</th>
      <td>172.000000</td>
      <td>172.0</td>
      <td>NaN</td>
      <td>355.0</td>
      <td>355.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Wilson Yip</th>
      <td>105.000000</td>
      <td>105.0</td>
      <td>NaN</td>
      <td>25.0</td>
      <td>25.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Wolfgang Becker</th>
      <td>121.000000</td>
      <td>121.0</td>
      <td>NaN</td>
      <td>31.0</td>
      <td>31.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Wolfgang Petersen</th>
      <td>151.714286</td>
      <td>1062.0</td>
      <td>70.698218</td>
      <td>249.0</td>
      <td>1743.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Woo-Suk Kang</th>
      <td>135.000000</td>
      <td>135.0</td>
      <td>NaN</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Woody Allen</th>
      <td>99.727273</td>
      <td>2194.0</td>
      <td>10.788803</td>
      <td>11000.0</td>
      <td>242000.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Wych Kaosayananda</th>
      <td>91.000000</td>
      <td>91.0</td>
      <td>NaN</td>
      <td>8.0</td>
      <td>8.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Xavier Beauvois</th>
      <td>122.000000</td>
      <td>122.0</td>
      <td>NaN</td>
      <td>22.0</td>
      <td>22.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Xavier Gens</th>
      <td>108.000000</td>
      <td>216.0</td>
      <td>19.798990</td>
      <td>87.0</td>
      <td>174.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Yarrow Cheney</th>
      <td>87.000000</td>
      <td>87.0</td>
      <td>NaN</td>
      <td>11.0</td>
      <td>11.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Yash Chopra</th>
      <td>184.000000</td>
      <td>368.0</td>
      <td>11.313708</td>
      <td>147.0</td>
      <td>294.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Yimou Zhang</th>
      <td>104.750000</td>
      <td>838.0</td>
      <td>22.114959</td>
      <td>611.0</td>
      <td>4888.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Yorgos Lanthimos</th>
      <td>94.000000</td>
      <td>94.0</td>
      <td>NaN</td>
      <td>252.0</td>
      <td>252.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Youssef Delara</th>
      <td>84.000000</td>
      <td>168.0</td>
      <td>5.656854</td>
      <td>8.0</td>
      <td>16.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Yuefeng Song</th>
      <td>88.000000</td>
      <td>88.0</td>
      <td>NaN</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Zach Braff</th>
      <td>104.000000</td>
      <td>208.0</td>
      <td>2.828427</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Zach Cregger</th>
      <td>90.000000</td>
      <td>90.0</td>
      <td>NaN</td>
      <td>138.0</td>
      <td>138.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Zack Snyder</th>
      <td>138.375000</td>
      <td>1107.0</td>
      <td>40.454339</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Zack Ward</th>
      <td>92.000000</td>
      <td>92.0</td>
      <td>NaN</td>
      <td>662.0</td>
      <td>662.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Zackary Adler</th>
      <td>110.000000</td>
      <td>110.0</td>
      <td>NaN</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Zak Penn</th>
      <td>94.000000</td>
      <td>94.0</td>
      <td>NaN</td>
      <td>87.0</td>
      <td>87.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Zal Batmanglij</th>
      <td>100.500000</td>
      <td>201.0</td>
      <td>21.920310</td>
      <td>129.0</td>
      <td>258.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>Zoran Lisinac</th>
      <td>108.000000</td>
      <td>108.0</td>
      <td>NaN</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Álex de la Iglesia</th>
      <td>104.000000</td>
      <td>104.0</td>
      <td>NaN</td>
      <td>275.0</td>
      <td>275.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Émile Gaudreault</th>
      <td>92.000000</td>
      <td>92.0</td>
      <td>NaN</td>
      <td>9.0</td>
      <td>9.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Éric Tessier</th>
      <td>99.000000</td>
      <td>99.0</td>
      <td>NaN</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Étienne Faure</th>
      <td>98.000000</td>
      <td>98.0</td>
      <td>NaN</td>
      <td>77.0</td>
      <td>77.0</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
<p>2398 rows × 6 columns</p>
</div>

In [36]:
# 不同的列用不同的统计量
grouped.agg({'duration':np.mean,'actor_1_facebook_likes':np.sum})

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>duration</th>
      <th>actor_1_facebook_likes</th>
    </tr>
    <tr>
      <th>director_name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>A. Raven Cruz</th>
      <td>97.000000</td>
      <td>639.0</td>
    </tr>
    <tr>
      <th>Aaron Hann</th>
      <td>87.000000</td>
      <td>160.0</td>
    </tr>
    <tr>
      <th>Aaron Schneider</th>
      <td>100.000000</td>
      <td>13000.0</td>
    </tr>
    <tr>
      <th>Aaron Seltzer</th>
      <td>85.000000</td>
      <td>3000.0</td>
    </tr>
    <tr>
      <th>Abel Ferrara</th>
      <td>99.000000</td>
      <td>812.0</td>
    </tr>
    <tr>
      <th>Adam Brooks</th>
      <td>112.000000</td>
      <td>16000.0</td>
    </tr>
    <tr>
      <th>Adam Carolla</th>
      <td>98.000000</td>
      <td>563.0</td>
    </tr>
    <tr>
      <th>Adam Goldberg</th>
      <td>111.000000</td>
      <td>2000.0</td>
    </tr>
    <tr>
      <th>Adam Green</th>
      <td>93.000000</td>
      <td>936.0</td>
    </tr>
    <tr>
      <th>Adam Jay Epstein</th>
      <td>76.000000</td>
      <td>387.0</td>
    </tr>
    <tr>
      <th>Adam Marcus</th>
      <td>91.000000</td>
      <td>935.0</td>
    </tr>
    <tr>
      <th>Adam McKay</th>
      <td>119.166667</td>
      <td>712000.0</td>
    </tr>
    <tr>
      <th>Adam Rapp</th>
      <td>98.000000</td>
      <td>11000.0</td>
    </tr>
    <tr>
      <th>Adam Rifkin</th>
      <td>95.000000</td>
      <td>1471.0</td>
    </tr>
    <tr>
      <th>Adam Shankman</th>
      <td>106.250000</td>
      <td>50796.0</td>
    </tr>
    <tr>
      <th>Adrian Lyne</th>
      <td>112.500000</td>
      <td>2516.0</td>
    </tr>
    <tr>
      <th>Adrienne Shelly</th>
      <td>108.000000</td>
      <td>597.0</td>
    </tr>
    <tr>
      <th>Agnieszka Holland</th>
      <td>104.000000</td>
      <td>60.0</td>
    </tr>
    <tr>
      <th>Agnieszka Wojtowicz-Vosloo</th>
      <td>104.000000</td>
      <td>14000.0</td>
    </tr>
    <tr>
      <th>Agustín Díaz Yanes</th>
      <td>145.000000</td>
      <td>10000.0</td>
    </tr>
    <tr>
      <th>Aki Kaurismäki</th>
      <td>93.000000</td>
      <td>232.0</td>
    </tr>
    <tr>
      <th>Akira Kurosawa</th>
      <td>168.000000</td>
      <td>319.0</td>
    </tr>
    <tr>
      <th>Akiva Goldsman</th>
      <td>118.000000</td>
      <td>20000.0</td>
    </tr>
    <tr>
      <th>Akiva Schaffer</th>
      <td>97.333333</td>
      <td>2118.0</td>
    </tr>
    <tr>
      <th>Al Franklin</th>
      <td>96.000000</td>
      <td>471.0</td>
    </tr>
    <tr>
      <th>Al Silliman Jr.</th>
      <td>93.000000</td>
      <td>12.0</td>
    </tr>
    <tr>
      <th>Alain Resnais</th>
      <td>104.000000</td>
      <td>412.0</td>
    </tr>
    <tr>
      <th>Alan Alda</th>
      <td>107.000000</td>
      <td>804.0</td>
    </tr>
    <tr>
      <th>Alan Cohn</th>
      <td>96.000000</td>
      <td>3000.0</td>
    </tr>
    <tr>
      <th>Alan J. Pakula</th>
      <td>126.000000</td>
      <td>29000.0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>William Phillips</th>
      <td>89.000000</td>
      <td>764.0</td>
    </tr>
    <tr>
      <th>William Sachs</th>
      <td>95.000000</td>
      <td>113.0</td>
    </tr>
    <tr>
      <th>William Shatner</th>
      <td>107.000000</td>
      <td>12000.0</td>
    </tr>
    <tr>
      <th>William Wyler</th>
      <td>172.000000</td>
      <td>749.0</td>
    </tr>
    <tr>
      <th>Wilson Yip</th>
      <td>105.000000</td>
      <td>461.0</td>
    </tr>
    <tr>
      <th>Wolfgang Becker</th>
      <td>121.000000</td>
      <td>65.0</td>
    </tr>
    <tr>
      <th>Wolfgang Petersen</th>
      <td>151.714286</td>
      <td>128669.0</td>
    </tr>
    <tr>
      <th>Woo-Suk Kang</th>
      <td>135.000000</td>
      <td>28.0</td>
    </tr>
    <tr>
      <th>Woody Allen</th>
      <td>99.727273</td>
      <td>184847.0</td>
    </tr>
    <tr>
      <th>Wych Kaosayananda</th>
      <td>91.000000</td>
      <td>349.0</td>
    </tr>
    <tr>
      <th>Xavier Beauvois</th>
      <td>122.000000</td>
      <td>186.0</td>
    </tr>
    <tr>
      <th>Xavier Gens</th>
      <td>108.000000</td>
      <td>2866.0</td>
    </tr>
    <tr>
      <th>Yarrow Cheney</th>
      <td>87.000000</td>
      <td>1000.0</td>
    </tr>
    <tr>
      <th>Yash Chopra</th>
      <td>184.000000</td>
      <td>16000.0</td>
    </tr>
    <tr>
      <th>Yimou Zhang</th>
      <td>104.750000</td>
      <td>35530.0</td>
    </tr>
    <tr>
      <th>Yorgos Lanthimos</th>
      <td>94.000000</td>
      <td>47.0</td>
    </tr>
    <tr>
      <th>Youssef Delara</th>
      <td>84.000000</td>
      <td>4000.0</td>
    </tr>
    <tr>
      <th>Yuefeng Song</th>
      <td>88.000000</td>
      <td>76.0</td>
    </tr>
    <tr>
      <th>Zach Braff</th>
      <td>104.000000</td>
      <td>17625.0</td>
    </tr>
    <tr>
      <th>Zach Cregger</th>
      <td>90.000000</td>
      <td>373.0</td>
    </tr>
    <tr>
      <th>Zack Snyder</th>
      <td>138.375000</td>
      <td>60986.0</td>
    </tr>
    <tr>
      <th>Zack Ward</th>
      <td>92.000000</td>
      <td>662.0</td>
    </tr>
    <tr>
      <th>Zackary Adler</th>
      <td>110.000000</td>
      <td>490.0</td>
    </tr>
    <tr>
      <th>Zak Penn</th>
      <td>94.000000</td>
      <td>87.0</td>
    </tr>
    <tr>
      <th>Zal Batmanglij</th>
      <td>100.500000</td>
      <td>10120.0</td>
    </tr>
    <tr>
      <th>Zoran Lisinac</th>
      <td>108.000000</td>
      <td>431.0</td>
    </tr>
    <tr>
      <th>Álex de la Iglesia</th>
      <td>104.000000</td>
      <td>439.0</td>
    </tr>
    <tr>
      <th>Émile Gaudreault</th>
      <td>92.000000</td>
      <td>636.0</td>
    </tr>
    <tr>
      <th>Éric Tessier</th>
      <td>99.000000</td>
      <td>50.0</td>
    </tr>
    <tr>
      <th>Étienne Faure</th>
      <td>98.000000</td>
      <td>19.0</td>
    </tr>
  </tbody>
</table>
<p>2398 rows × 2 columns</p>
</div>

In [57]:
# transformation 对组数据做标准化或填充缺省值

# 对组数值型数据做标准化处理
# （数值-平均数）/ 标准差

# 由于原数值中有空值，会造成数据的不一致，因此用fillna(0)填充0值
df2 = df.fillna(0)
grouped = df2.groupby('director_name')

grouped.filter(grouped['duration'] grouped['duration'] > 150 )



#.filter(lambda g: g.mean() > 150)
# filtration 对组数据做过滤处理

0       178.0
8       141.0
17      173.0
20      164.0
23      186.0
25      201.0
26      194.0
99      182.0
105      98.0
147     196.0
221     130.0
270     171.0
288     153.0
291     141.0
337     135.0
339     192.0
340     172.0
399     124.0
462     154.0
499     177.0
576     152.0
606     171.0
681     135.0
712     189.0
794     173.0
827     136.0
883     280.0
895     170.0
957     127.0
1051    123.0
        ...
3412    180.0
3455    153.0
3466    175.0
3510    192.0
3532    177.0
3537     88.0
3575    107.0
3588    152.0
3685    157.0
3766    145.0
3775    108.0
3821    148.0
3890    152.0
3903    172.0
3958    168.0
4066    161.0
4077    186.0
4238    172.0
4351    160.0
4365    155.0
4396    113.0
4498    142.0
4572    167.0
4584    135.0
4593    160.0
4682    106.0
4694    201.0
4708    215.0
4747    202.0
4897     99.0
Name: duration, Length: 119, dtype: float64

In [40]:
# 定义一个标准化函数
z_score = lambda s : (s - s.mean()) / s.std()

In [42]:
df2.shape

(5043, 28)

In [52]:
grouped['duration','actor_1_facebook_likes'].transform(z_score)

grouped['duration'].filter(lambda g: g.mean() > 150)

0       178.0
8       141.0
17      173.0
20      164.0
23      186.0
25      201.0
26      194.0
99      182.0
105      98.0
147     196.0
221     130.0
270     171.0
288     153.0
291     141.0
337     135.0
339     192.0
340     172.0
399     124.0
462     154.0
499     177.0
576     152.0
606     171.0
681     135.0
712     189.0
794     173.0
827     136.0
883     280.0
895     170.0
957     127.0
1051    123.0
        ...
3412    180.0
3455    153.0
3466    175.0
3510    192.0
3532    177.0
3537     88.0
3575    107.0
3588    152.0
3685    157.0
3766    145.0
3775    108.0
3821    148.0
3890    152.0
3903    172.0
3958    168.0
4066    161.0
4077    186.0
4238    172.0
4351    160.0
4365    155.0
4396    113.0
4498    142.0
4572    167.0
4584    135.0
4593    160.0
4682    106.0
4694    201.0
4708    215.0
4747    202.0
4897     99.0
Name: duration, Length: 119, dtype: float64

In [58]:
# 数据过滤

# 每个组里面小于2的剔除
grouped.filter(lambda g: len(g) > 1)

grouped.filter(lambda g: len(g) > 1)['director_name'].value_counts()

0                       104
Steven Spielberg         26
Woody Allen              22
Clint Eastwood           20
Martin Scorsese          20
Ridley Scott             17
Steven Soderbergh        16
Tim Burton               16
Spike Lee                16
Renny Harlin             15
Oliver Stone             14
John Carpenter           13
Barry Levinson           13
Robert Zemeckis          13
Joel Schumacher          13
Sam Raimi                13
Ron Howard               13
Michael Bay              13
Robert Rodriguez         13
Tony Scott               12
Wes Craven               12
Brian De Palma           12
Peter Jackson            12
Kevin Smith              12
Richard Donner           12
Shawn Levy               12
Richard Linklater        11
Chris Columbus           11
Francis Ford Coppola     11
Rob Cohen                11
                       ...
Herbert Ross              2
Anne Fontaine             2
Julian Schnabel           2
Michael Lembeck           2
Vincent Gallo             2
Steve Rash                2
Steve Boyum               2
Stephen Norrington        2
David DeCoteau            2
Brian Koppelman           2
Jerry Jameson             2
Alejandro Monteverde      2
Jake Schreier             2
Kevin Spacey              2
Todd Graff                2
Tommy Lee Jones           2
Gary Trousdale            2
Larry Clark               2
Sheldon Lettich           2
Simon Curtis              2
Bob Rafelson              2
Troy Duffy                2
Michael Tollin            2
Whit Stillman             2
Mark Herman               2
Douglas Aarniokoski       2
Deepa Mehta               2
Jean-Luc Godard           2
Joe Swanberg              2
David Mamet               2
Name: director_name, Length: 895, dtype: int64

In [68]:
# 表的连接 join
# 样本数据
df1 = pd.DataFrame({'key1': ['K0', 'K1', 'K2', 'K1'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                     'C': ['C0', 'C1', 'C2', 'C3'],
                     'D': ['D0', 'D1', 'D2', 'D3']},
                     )
 

df2 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                     'key2': ['K0', 'K0', 'K0', 'K0'],
                     'A': ['C4', 'C5', 'C6', 'C7'],
                     'B': ['D4', 'D5', 'D6', 'D7']},
                      )
 

df3 = pd.DataFrame({'key3': ['A8', 'A9', 'A10', 'A11'],
                     'key4': ['B8', 'B9', 'B10', 'B11'],
                     'E': ['C8', 'C9', 'C10', 'C11'],
                     'F': ['D8', 'D9', 'D10', 'D11']},
                     )

In [92]:
# concat:组装相同的数据结构

# result = pd.concat([df1, df2, df3])
# result
result1 = pd.merge(df1, df2, how='left', on= ['key1'])

In [69]:
df1

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>key1</th>
      <th>key2</th>
      <th>C</th>
      <th>D</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>K0</td>
      <td>K0</td>
      <td>C0</td>
      <td>D0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>K1</td>
      <td>K1</td>
      <td>C1</td>
      <td>D1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>K2</td>
      <td>K0</td>
      <td>C2</td>
      <td>D2</td>
    </tr>
    <tr>
      <th>3</th>
      <td>K1</td>
      <td>K1</td>
      <td>C3</td>
      <td>D3</td>
    </tr>
  </tbody>
</table>
</div>

In [76]:
df2

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>key1</th>
      <th>key2</th>
      <th>A</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>K0</td>
      <td>K0</td>
      <td>C4</td>
      <td>D4</td>
    </tr>
    <tr>
      <th>1</th>
      <td>K1</td>
      <td>K0</td>
      <td>C5</td>
      <td>D5</td>
    </tr>
    <tr>
      <th>2</th>
      <td>K1</td>
      <td>K0</td>
      <td>C6</td>
      <td>D6</td>
    </tr>
    <tr>
      <th>3</th>
      <td>K2</td>
      <td>K0</td>
      <td>C7</td>
      <td>D7</td>
    </tr>
  </tbody>
</table>
</div>

In [79]:
df2.set_index(['key1','key2'], inplace=True)

KeyError: 'key1'

In [80]:
df1.set_index(['key1','key2'], inplace=True)

KeyError: 'key1'

In [81]:
df1

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>C</th>
      <th>D</th>
    </tr>
    <tr>
      <th>key1</th>
      <th>key2</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>K0</th>
      <th>K0</th>
      <td>C0</td>
      <td>D0</td>
    </tr>
    <tr>
      <th>K1</th>
      <th>K1</th>
      <td>C1</td>
      <td>D1</td>
    </tr>
    <tr>
      <th>K2</th>
      <th>K0</th>
      <td>C2</td>
      <td>D2</td>
    </tr>
    <tr>
      <th>K1</th>
      <th>K1</th>
      <td>C3</td>
      <td>D3</td>
    </tr>
  </tbody>
</table>
</div>

In [82]:
df2

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>A</th>
      <th>B</th>
    </tr>
    <tr>
      <th>key1</th>
      <th>key2</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>K0</th>
      <th>K0</th>
      <td>C4</td>
      <td>D4</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">K1</th>
      <th>K0</th>
      <td>C5</td>
      <td>D5</td>
    </tr>
    <tr>
      <th>K0</th>
      <td>C6</td>
      <td>D6</td>
    </tr>
    <tr>
      <th>K2</th>
      <th>K0</th>
      <td>C7</td>
      <td>D7</td>
    </tr>
  </tbody>
</table>
</div>

In [89]:
pd.merge(df1, df2, left_index=True, right_index= True)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>C</th>
      <th>D</th>
      <th>A</th>
      <th>B</th>
    </tr>
    <tr>
      <th>key1</th>
      <th>key2</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>K0</th>
      <th>K0</th>
      <td>C0</td>
      <td>D0</td>
      <td>C4</td>
      <td>D4</td>
    </tr>
    <tr>
      <th>K2</th>
      <th>K0</th>
      <td>C2</td>
      <td>D2</td>
      <td>C7</td>
      <td>D7</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
# 两个不同的
pd.merge(df1, df2, left_on= ['key1','key2'], right_on= ['key3','key4'])

pd.reset_index #将index 索引重新放到 column上

# 索引和列名组合
pd.merge(left, right, left_index= True, right_on=['key3','key4'])

In [98]:
# 数据透视表
pd.pivot_table(df, values=['duration'], columns = ['director_name'], index = ['color'], 
               aggfunc=[np.sum, np.mean])

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }

    .dataframe thead tr:last-of-type th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="10" halign="left">sum</th>
      <th>...</th>
      <th colspan="10" halign="left">mean</th>
    </tr>
    <tr>
      <th></th>
      <th colspan="10" halign="left">duration</th>
      <th>...</th>
      <th colspan="10" halign="left">duration</th>
    </tr>
    <tr>
      <th>director_name</th>
      <th>A. Raven Cruz</th>
      <th>Aaron Hann</th>
      <th>Aaron Schneider</th>
      <th>Aaron Seltzer</th>
      <th>Abel Ferrara</th>
      <th>Adam Brooks</th>
      <th>Adam Carolla</th>
      <th>Adam Goldberg</th>
      <th>Adam Green</th>
      <th>Adam Jay Epstein</th>
      <th>...</th>
      <th>Zach Cregger</th>
      <th>Zack Snyder</th>
      <th>Zack Ward</th>
      <th>Zak Penn</th>
      <th>Zal Batmanglij</th>
      <th>Zoran Lisinac</th>
      <th>Álex de la Iglesia</th>
      <th>Émile Gaudreault</th>
      <th>Éric Tessier</th>
      <th>Étienne Faure</th>
    </tr>
    <tr>
      <th>color</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Black and White</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>...</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>Color</th>
      <td>97.0</td>
      <td>87.0</td>
      <td>100.0</td>
      <td>85.0</td>
      <td>99.0</td>
      <td>112.0</td>
      <td>98.0</td>
      <td>111.0</td>
      <td>93.0</td>
      <td>76.0</td>
      <td>...</td>
      <td>90.0</td>
      <td>138.375</td>
      <td>92.0</td>
      <td>94.0</td>
      <td>100.5</td>
      <td>108.0</td>
      <td>104.0</td>
      <td>92.0</td>
      <td>99.0</td>
      <td>98.0</td>
    </tr>
  </tbody>
</table>
<p>2 rows × 4765 columns</p>
</div>

In [100]:
# 计算两个因子的交叉频率,卡方检验，计算两个因子之间的相关性
pd.crosstab(df['director_name'],df['color'], margins = True)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>color</th>
      <th>Black and White</th>
      <th>Color</th>
      <th>All</th>
    </tr>
    <tr>
      <th>director_name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>A. Raven Cruz</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Aaron Hann</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Aaron Schneider</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Aaron Seltzer</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Abel Ferrara</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Adam Brooks</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Adam Carolla</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Adam Goldberg</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Adam Green</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Adam Jay Epstein</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Adam Marcus</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Adam McKay</th>
      <td>0</td>
      <td>6</td>
      <td>6</td>
    </tr>
    <tr>
      <th>Adam Rapp</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Adam Rifkin</th>
      <td>0</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>Adam Shankman</th>
      <td>0</td>
      <td>8</td>
      <td>8</td>
    </tr>
    <tr>
      <th>Adrian Lyne</th>
      <td>0</td>
      <td>4</td>
      <td>4</td>
    </tr>
    <tr>
      <th>Adrienne Shelly</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Agnieszka Holland</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Agnieszka Wojtowicz-Vosloo</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Agustín Díaz Yanes</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Aki Kaurismäki</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Akira Kurosawa</th>
      <td>1</td>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>Akiva Goldsman</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Akiva Schaffer</th>
      <td>0</td>
      <td>3</td>
      <td>3</td>
    </tr>
    <tr>
      <th>Al Franklin</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Al Silliman Jr.</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Alain Resnais</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Alan Alda</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Alan Cohn</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Alan J. Pakula</th>
      <td>0</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>William Phillips</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>William Sachs</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>William Shatner</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>William Wyler</th>
      <td>1</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Wilson Yip</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Wolfgang Becker</th>
      <td>1</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Wolfgang Petersen</th>
      <td>0</td>
      <td>7</td>
      <td>7</td>
    </tr>
    <tr>
      <th>Woo-Suk Kang</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Woody Allen</th>
      <td>2</td>
      <td>20</td>
      <td>22</td>
    </tr>
    <tr>
      <th>Wych Kaosayananda</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Xavier Beauvois</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Xavier Gens</th>
      <td>0</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>Yarrow Cheney</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Yash Chopra</th>
      <td>0</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>Yimou Zhang</th>
      <td>2</td>
      <td>6</td>
      <td>8</td>
    </tr>
    <tr>
      <th>Yorgos Lanthimos</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Youssef Delara</th>
      <td>0</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>Yuefeng Song</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Zach Braff</th>
      <td>0</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>Zach Cregger</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Zack Snyder</th>
      <td>0</td>
      <td>8</td>
      <td>8</td>
    </tr>
    <tr>
      <th>Zack Ward</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Zak Penn</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Zal Batmanglij</th>
      <td>0</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>Zoran Lisinac</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Álex de la Iglesia</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Émile Gaudreault</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Éric Tessier</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>Étienne Faure</th>
      <td>0</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <th>All</th>
      <td>206</td>
      <td>4716</td>
      <td>4922</td>
    </tr>
  </tbody>
</table>
<p>2388 rows × 3 columns</p>
</div>